"use client"

import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from "react"
import { CalendarClock, CheckCircle2, Clock3, CopyPlus, Eye, Megaphone, MessageCircleMore, Save, Search, Send, Users, XCircle } from "lucide-react"
import { useAppContext } from "@/components/app-context"
import { useToast } from "@/components/toast-provider"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { apiRequest } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"
import { cn } from "@/lib/utils"

type Purpose="MARKETING"|"RENEWAL"|"REMINDER"|"ANNOUNCEMENT"|"FOLLOW_UP"|"OTHER"
type AudienceType="SINGLE_MEMBER"|"SINGLE_LEAD"|"MEMBER_SEGMENT"|"LEAD_SEGMENT"|"ALL_MEMBERS"|"ALL_LEADS"
type Template={id:string;branchId?:string;name:string;purpose:Purpose;title:string;body:string;status:"ACTIVE"|"INACTIVE";version:number;updatedAt:string}
type Campaign={id:string;branchId?:string;name:string;purpose:Purpose;title:string;audienceType:AudienceType;channels:string[];scheduledAt:string;status:"SCHEDULED"|"PROCESSING"|"COMPLETED"|"CANCELLED"|"FAILED";recipientCount:number;inAppDeliveredCount:number;whatsappEligibleCount:number;skippedCount:number;readCount:number;failureReason?:string;version:number}
type Preview={total:number;inAppEligible:number;whatsappEligible:number;withoutSystemAccount:number;samples:Array<{recipientId:string;name:string;memberNumber?:string;branchName:string;hasSystemAccount:boolean;subscriptionEndDate?:string}>}
type SearchRow={id:string;name?:string;fullName?:string;memberNumber?:string;phoneE164?:string;status?:string}
type CommunicationContext=ReturnType<typeof useAppContext>
type ComposerProps={purpose:Purpose;setPurpose:Dispatch<SetStateAction<Purpose>>;audienceType:AudienceType;setAudienceType:Dispatch<SetStateAction<AudienceType>>;scope:"BRANCH"|"ORGANIZATION";setScope:Dispatch<SetStateAction<"BRANCH"|"ORGANIZATION">>;organizationWide:boolean;canManageTemplates:boolean;context:CommunicationContext;templates:Template[];templateId:string;selectTemplate:(id:string)=>void;campaignName:string;setCampaignName:Dispatch<SetStateAction<string>>;title:string;setTitle:Dispatch<SetStateAction<string>>;body:string;setBody:Dispatch<SetStateAction<string>>;expiryDays:number;setExpiryDays:Dispatch<SetStateAction<number>>;leadStatuses:string[];setLeadStatuses:Dispatch<SetStateAction<string[]>>;targetSearch:string;setTargetSearch:Dispatch<SetStateAction<string>>;targets:SearchRow[];targetId:string;setTargetId:Dispatch<SetStateAction<string>>;searching:boolean;preview?:Preview;runPreview:()=>Promise<void>;previewing:boolean;timing:"NOW"|"SCHEDULED";setTiming:Dispatch<SetStateAction<"NOW"|"SCHEDULED">>;scheduledAt:string;setScheduledAt:Dispatch<SetStateAction<string>>;busy:boolean;submit:()=>Promise<void>;setTemplateEditor:Dispatch<SetStateAction<Template|"NEW"|undefined>>}

const purposes:Record<Purpose,string>={MARKETING:"رسالة ترويجية",RENEWAL:"تجديد اشتراك",REMINDER:"تذكير",ANNOUNCEMENT:"إعلان عام",FOLLOW_UP:"متابعة",OTHER:"رسالة أخرى"}
const audienceOptions:Array<{value:AudienceType;label:string;description:string}>=[
 {value:"SINGLE_MEMBER",label:"عضو محدد",description:"رسالة شخصية لعضو واحد"},
 {value:"MEMBER_SEGMENT",label:"اشتراكات تنتهي قريبًا",description:"استهداف الأعضاء حسب موعد انتهاء الاشتراك"},
 {value:"ALL_MEMBERS",label:"كل الأعضاء النشطين",description:"جميع أعضاء النطاق المختار"},
 {value:"SINGLE_LEAD",label:"عميل محتمل محدد",description:"شخص واحد من العملاء المحتملين"},
 {value:"LEAD_SEGMENT",label:"مجموعة عملاء محتملين",description:"حسب مرحلة المتابعة"},
 {value:"ALL_LEADS",label:"كل العملاء المحتملين",description:"جميع العملاء المفتوحين في النطاق"},
]
const statusLabels:Record<Campaign["status"],string>={SCHEDULED:"مجدولة",PROCESSING:"جارٍ الإرسال",COMPLETED:"تم الإرسال",CANCELLED:"ملغاة",FAILED:"تعذر الإرسال"}
const inputClass="h-11 rounded-xl border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15"

export function CommunicationCenter(){
 const context=useAppContext(),toast=useToast();const[tab,setTab]=useState<"compose"|"campaigns"|"templates">("compose")
 const[templates,setTemplates]=useState<Template[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
 const[purpose,setPurpose]=useState<Purpose>("ANNOUNCEMENT"),[audienceType,setAudienceType]=useState<AudienceType>("SINGLE_MEMBER"),[scope,setScope]=useState<"BRANCH"|"ORGANIZATION">("BRANCH")
 const[title,setTitle]=useState(""),[body,setBody]=useState(""),[campaignName,setCampaignName]=useState(""),[templateId,setTemplateId]=useState("")
 const[expiryDays,setExpiryDays]=useState(7),[leadStatuses,setLeadStatuses]=useState<string[]>(["NEW","CONTACTED","QUALIFIED","TRIAL_SCHEDULED"])
 const[targetSearch,setTargetSearch]=useState(""),[targets,setTargets]=useState<SearchRow[]>([]),[targetId,setTargetId]=useState(""),[searching,setSearching]=useState(false)
 const[timing,setTiming]=useState<"NOW"|"SCHEDULED">("NOW"),[scheduledAt,setScheduledAt]=useState("")
 const[preview,setPreview]=useState<Preview>(),[previewing,setPreviewing]=useState(false),[templateEditor,setTemplateEditor]=useState<Template|"NEW">()
 const organizationWide=context.grants.some(grant=>grant.organizationId===context.organizationId&&grant.permission==="notifications.send"&&grant.scopeType==="ORGANIZATION")
 const canManageTemplates=context.canAccess(["notification-templates.manage"]),canReadTemplates=context.canAccess(["notification-templates.read"]),canReadCampaigns=context.canAccess(["notifications.read"])
 const branchId=scope==="BRANCH"?context.branchId:undefined

 async function load(){if(!context.organizationId)return;setLoading(true);try{const[t,c]=await Promise.all([canReadTemplates?apiRequest<Template[]>(`/organizations/${context.organizationId}/communication-templates?includeInactive=true`):Promise.resolve({data:[] as Template[]}),canReadCampaigns?apiRequest<Campaign[]>(`/organizations/${context.organizationId}/communication-campaigns?limit=100`):Promise.resolve({data:[] as Campaign[]})]);setTemplates(t.data??[]);setCampaigns(c.data??[])}catch(reason){toast.error(humanError(reason,"تعذر تحميل مركز التواصل."))}finally{setLoading(false)}}
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[context.organizationId]) // eslint-disable-line react-hooks/exhaustive-deps

 useEffect(()=>{const frame=requestAnimationFrame(()=>{setPreview(undefined);setTargetId("");setTargets([]);setTargetSearch("")});return()=>cancelAnimationFrame(frame)},[audienceType,scope])
 useEffect(()=>{if(!["SINGLE_MEMBER","SINGLE_LEAD"].includes(audienceType)||targetSearch.trim().length<2||!context.organizationId)return;let cancelled=false;const timer=window.setTimeout(async()=>{setSearching(true);try{const isMember=audienceType==="SINGLE_MEMBER";const path=isMember?`/organizations/${context.organizationId}/members?${branchId?`branchId=${branchId}&`:""}search=${encodeURIComponent(targetSearch)}&limit=25`:`/organizations/${context.organizationId}/crm/leads?${branchId?`branchId=${branchId}&`:""}search=${encodeURIComponent(targetSearch)}&limit=25`;const response=await apiRequest<unknown>(path);if(!cancelled)setTargets(list(response.data))}catch{if(!cancelled)setTargets([])}finally{if(!cancelled)setSearching(false)}},350);return()=>{cancelled=true;window.clearTimeout(timer)}},[audienceType,branchId,context.organizationId,targetSearch])

 const filter=useMemo(()=>audienceFilter(audienceType,targetId,expiryDays,leadStatuses),[audienceType,targetId,expiryDays,leadStatuses])
 async function runPreview(){if(!validAudience(audienceType,targetId)){toast.warning("اختر المستلم أولًا.");return}setPreviewing(true);try{const response=await apiRequest<Preview>(`/organizations/${context.organizationId}/communication-campaigns/audience-preview`,{method:"POST",body:JSON.stringify({...(branchId?{branchId}:{}),audienceType,audienceFilter:filter})});setPreview(response.data)}catch(reason){toast.error(humanError(reason,"تعذر معاينة المستلمين."))}finally{setPreviewing(false)}}
 function selectTemplate(id:string){setTemplateId(id);const value=templates.find(item=>item.id===id);if(value){setPurpose(value.purpose);setTitle(value.title);setBody(value.body);setCampaignName(value.name)}}
 async function submit(){if(!title.trim()||!body.trim()||!campaignName.trim()){toast.warning("أدخل اسم الحملة وعنوان الرسالة ونصها.");return}if(!validAudience(audienceType,targetId)){toast.warning("حدد المستلمين قبل الإرسال.");return}if(timing==="SCHEDULED"&&!scheduledAt){toast.warning("حدد موعد الإرسال.");return}setBusy(true);try{const response=await apiRequest<Campaign>(`/organizations/${context.organizationId}/communication-campaigns`,{method:"POST",body:JSON.stringify({...(branchId?{branchId}:{}),...(templateId?{templateId}:{}),name:campaignName.trim(),purpose,title:title.trim(),body:body.trim(),audienceType,audienceFilter:filter,channels:["IN_APP"],...(timing==="SCHEDULED"?{scheduledAt:new Date(scheduledAt).toISOString()}: {})})});toast.success(timing==="NOW"?"تم إرسال الرسالة داخل النظام.":"تمت جدولة الرسالة بنجاح.");setCampaigns(current=>[response.data,...current.filter(item=>item.id!==response.data.id)]);setPreview(undefined);setTab("campaigns")}catch(reason){toast.error(humanError(reason,"تعذر إرسال الرسالة."))}finally{setBusy(false)}}
 async function cancel(campaign:Campaign){try{const response=await apiRequest<Campaign>(`/organizations/${context.organizationId}/communication-campaigns/${campaign.id}/cancellations`,{method:"POST",body:JSON.stringify({...(campaign.branchId?{branchId:campaign.branchId}:{}),expectedVersion:campaign.version})});setCampaigns(rows=>rows.map(row=>row.id===campaign.id?response.data:row));toast.success("تم إلغاء الرسالة المجدولة.")}catch(reason){toast.error(humanError(reason,"تعذر إلغاء الرسالة."))}}

 return <div dir="rtl" className="space-y-6">
  <section className="overflow-hidden rounded-3xl border border-primary/20 bg-gradient-to-l from-primary/10 via-card to-card p-6 sm:p-8">
   <Badge variant="warning"><Megaphone className="size-3.5"/> مركز التواصل</Badge><div className="mt-4 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h1 className="text-2xl font-black sm:text-4xl">رسائل الأعضاء والعملاء المحتملين</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">أنشئ رسالة واضحة، اختر جمهورها، أرسلها الآن أو حدد موعدًا لها. تظهر الرسائل داخل حساب العضو فورًا، وتصبح واتساب متاحة بعد ربط مزود الخدمة.</p></div><div className="flex gap-2"><Metric value={campaigns.filter(item=>item.status==="SCHEDULED").length} label="رسائل مجدولة"/><Metric value={campaigns.filter(item=>item.status==="COMPLETED").length} label="حملات مرسلة"/></div></div>
  </section>
  <div className="flex flex-wrap gap-2 rounded-2xl border bg-card p-2">{([{key:"compose",label:"إنشاء رسالة",icon:Send},{key:"campaigns",label:"سجل الرسائل",icon:Clock3},{key:"templates",label:"الرسائل المحفوظة",icon:CopyPlus}] as const).map(item=><Button key={item.key} variant={tab===item.key?"default":"ghost"} size="lg" onClick={()=>setTab(item.key)}><item.icon/>{item.label}</Button>)}</div>
  {loading?<Loading/>:tab==="compose"?<Composer {...{purpose,setPurpose,audienceType,setAudienceType,scope,setScope,organizationWide,canManageTemplates,context,templates,templateId,selectTemplate,campaignName,setCampaignName,title,setTitle,body,setBody,expiryDays,setExpiryDays,leadStatuses,setLeadStatuses,targetSearch,setTargetSearch,targets,targetId,setTargetId,searching,preview,runPreview,previewing,timing,setTiming,scheduledAt,setScheduledAt,busy,submit,setTemplateEditor}}/>:tab==="campaigns"?<CampaignList campaigns={campaigns} cancel={cancel}/>:<TemplateList templates={templates} edit={setTemplateEditor} canManage={canManageTemplates}/>} 
  {templateEditor&&<TemplateDialog value={templateEditor} organizationId={context.organizationId} branchId={branchId} close={()=>setTemplateEditor(undefined)} saved={async()=>{setTemplateEditor(undefined);await load()}}/>}
 </div>
}

function Composer(props:ComposerProps){const{purpose,setPurpose,audienceType,setAudienceType,scope,setScope,organizationWide,canManageTemplates,context,templates,templateId,selectTemplate,campaignName,setCampaignName,title,setTitle,body,setBody,expiryDays,setExpiryDays,leadStatuses,setLeadStatuses,targetSearch,setTargetSearch,targets,targetId,setTargetId,searching,preview,runPreview,previewing,timing,setTiming,scheduledAt,setScheduledAt,busy,submit,setTemplateEditor}=props
 return <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,.65fr)]">
  <Card><CardHeader><div><CardTitle className="text-xl">محتوى الرسالة</CardTitle><CardDescription className="mt-1">اكتب الرسالة مرة أو استخدم رسالة محفوظة.</CardDescription></div>{canManageTemplates&&<Button variant="outline" onClick={()=>setTemplateEditor("NEW")}><Save/>حفظ رسالة متكررة</Button>}</CardHeader><CardContent className="space-y-5">
   <Field label="استخدام رسالة محفوظة"><select className={cn(inputClass,"w-full")} value={templateId} onChange={e=>selectTemplate(e.target.value)}><option value="">ابدأ برسالة جديدة</option>{templates.filter((x:Template)=>x.status==="ACTIVE").map((x:Template)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
   <div className="grid gap-4 md:grid-cols-2"><Field label="الغرض من الرسالة"><select className={cn(inputClass,"w-full")} value={purpose} onChange={e=>setPurpose(e.target.value as Purpose)}>{Object.entries(purposes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="اسم داخلي للحملة" hint="لا يظهر للمستلم"><Input className="h-11" value={campaignName} onChange={e=>setCampaignName(e.target.value)} placeholder="مثال: تذكير تجديد أغسطس"/></Field></div>
   <Field label="عنوان الإشعار"><Input className="h-11" value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان مختصر وواضح" maxLength={160}/></Field>
   <Field label="نص الرسالة"><textarea className="min-h-44 w-full resize-y rounded-xl border bg-background p-4 text-sm leading-7 outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" value={body} onChange={e=>setBody(e.target.value)} placeholder="اكتب رسالتك هنا..." maxLength={4096}/><div className="mt-2 flex flex-wrap gap-2">{[["{{name}}","اسم المستلم"],["{{memberNumber}}","رقم العضوية"],["{{subscriptionEndDate}}","انتهاء الاشتراك"],["{{branchName}}","اسم الفرع"]].map(([token,label])=><button type="button" key={token} onClick={()=>setBody((v:string)=>`${v}${v?" ":""}${token}`)} className="rounded-lg border px-2.5 py-1.5 text-xs text-muted-foreground hover:border-primary hover:text-foreground">+ {label}</button>)}</div></Field>
  </CardContent></Card>
  <div className="space-y-6"><Card><CardHeader><div><CardTitle>المستلمون</CardTitle><CardDescription className="mt-1">حدد من سيستقبل الرسالة.</CardDescription></div><Users className="text-primary"/></CardHeader><CardContent className="space-y-4">
   {organizationWide&&<Field label="نطاق الإرسال"><div className="grid grid-cols-2 gap-2"><Choice active={scope==="BRANCH"} onClick={()=>setScope("BRANCH")} label={context.branches.find(branch=>branch.id===context.branchId)?.nameAr??"الفرع الحالي"}/><Choice active={scope==="ORGANIZATION"} onClick={()=>setScope("ORGANIZATION")} label="كل فروع النادي"/></div></Field>}
   <Field label="الجمهور"><select className={cn(inputClass,"w-full")} value={audienceType} onChange={e=>setAudienceType(e.target.value as AudienceType)}>{audienceOptions.map(x=><option key={x.value} value={x.value}>{x.label} — {x.description}</option>)}</select></Field>
   {["SINGLE_MEMBER","SINGLE_LEAD"].includes(audienceType)&&<Field label={audienceType==="SINGLE_MEMBER"?"ابحث بالاسم أو رقم العضوية":"ابحث باسم العميل أو رقم الجوال"}><div className="relative"><Search className="absolute right-3 top-3.5 size-4 text-muted-foreground"/><Input className="h-11 pr-10" value={targetSearch} onChange={e=>setTargetSearch(e.target.value)} placeholder="اكتب حرفين على الأقل..."/></div>{searching?<p className="mt-2 text-xs text-muted-foreground">جارٍ البحث...</p>:targets.length>0?<div className="mt-2 max-h-48 space-y-1 overflow-y-auto rounded-xl border p-1">{targets.map((row:SearchRow)=><button type="button" key={row.id} onClick={()=>setTargetId(row.id)} className={cn("flex w-full items-center justify-between rounded-lg p-2.5 text-right text-sm hover:bg-secondary",targetId===row.id&&"bg-primary/15 ring-1 ring-primary")}><span className="font-bold">{row.name??row.fullName}</span><span className="text-xs text-muted-foreground">{row.memberNumber??row.phoneE164??row.status}</span></button>)}</div>:null}</Field>}
   {audienceType==="MEMBER_SEGMENT"&&<Field label="ينتهي الاشتراك خلال"><div className="flex items-center gap-2"><Input type="number" min={1} max={365} className="h-11" value={expiryDays} onChange={e=>setExpiryDays(Number(e.target.value))}/><span className="shrink-0 text-sm text-muted-foreground">يومًا</span></div></Field>}
   {["LEAD_SEGMENT","ALL_LEADS"].includes(audienceType)&&<Field label="مراحل العملاء المحتملين"><div className="flex flex-wrap gap-2">{[["NEW","جديد"],["CONTACTED","تم التواصل"],["QUALIFIED","مؤهل"],["TRIAL_SCHEDULED","تجربة مجدولة"]].map(([v,l])=><button type="button" key={v} onClick={()=>setLeadStatuses((xs:string[])=>xs.includes(v)?xs.filter(x=>x!==v):[...xs,v])} className={cn("rounded-lg border px-2.5 py-1.5 text-xs",leadStatuses.includes(v)&&"border-primary bg-primary/15 text-primary")}>{l}</button>)}</div></Field>}
   {audienceType.includes("LEAD")&&<p className="rounded-xl border border-amber-500/25 bg-amber-500/8 p-3 text-xs leading-6 text-amber-700 dark:text-amber-400">العملاء المحتملون لا يملكون حساب عضو داخل النظام. يمكنك تجهيز الجمهور ومعاينته الآن، وسيصبح الإرسال إليهم متاحًا عند تشغيل قناة واتساب.</p>}
   <Button className="w-full" variant="outline" size="lg" onClick={runPreview} disabled={previewing}><Eye/>{previewing?"جارٍ حساب الجمهور...":"معاينة المستلمين"}</Button>
   {preview&&<div className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><p className="font-black">{preview.total.toLocaleString("ar-SA")} مستلم مطابق</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>لديهم حساب: <b>{preview.inAppEligible}</b></span><span>دون حساب: <b>{preview.withoutSystemAccount}</b></span></div>{preview.withoutSystemAccount>0&&<p className="mt-3 text-xs leading-5 text-amber-700 dark:text-amber-400">لن تصل رسالة داخل النظام لمن لا يملك حسابًا مرتبطًا. سيظهرون بوضوح في نتيجة الحملة.</p>}<div className="mt-3 flex flex-wrap gap-1">{preview.samples.slice(0,5).map(sample=><Badge key={sample.recipientId} variant="secondary">{sample.name}{sample.memberNumber?` · ${sample.memberNumber}`:""}</Badge>)}</div></div>}
  </CardContent></Card>
  <Card><CardHeader><CardTitle>القناة والموعد</CardTitle><MessageCircleMore className="text-primary"/></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-primary bg-primary/10 p-3"><p className="flex items-center gap-2 text-sm font-bold"><CheckCircle2 className="size-4 text-emerald-500"/> داخل النظام</p><p className="mt-1 text-[11px] text-muted-foreground">متاحة الآن</p></div><div aria-disabled="true" className="rounded-xl border border-dashed p-3 opacity-55"><p className="text-sm font-bold">واتساب</p><Badge className="mt-1" variant="warning">قريبًا</Badge></div><div aria-disabled="true" className="rounded-xl border border-dashed p-3 opacity-55"><p className="text-sm font-bold">النظام + واتساب</p><Badge className="mt-1" variant="warning">قريبًا</Badge></div></div><p className="text-xs leading-6 text-muted-foreground">لن يتم إرسال أي رسالة واتساب قبل ربط المزود. القناة المختارة حاليًا هي إشعارات النظام فقط.</p><div className="grid grid-cols-2 gap-2"><Choice active={timing==="NOW"} onClick={()=>setTiming("NOW")} label="إرسال الآن"/><Choice active={timing==="SCHEDULED"} onClick={()=>setTiming("SCHEDULED")} label="تحديد موعد"/></div>{timing==="SCHEDULED"&&<Input type="datetime-local" className="h-11" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} min={localDateTime(new Date())}/>}<Button size="lg" className="w-full" onClick={submit} disabled={busy||audienceType.includes("LEAD")}>{timing==="NOW"?<Send/>:<CalendarClock/>}{audienceType.includes("LEAD")?"يتاح عند تشغيل واتساب":busy?"جارٍ الحفظ...":timing==="NOW"?"إرسال داخل النظام":"جدولة الرسالة"}</Button></CardContent></Card></div>
 </div>
}

function CampaignList({campaigns,cancel}:{campaigns:Campaign[];cancel:(value:Campaign)=>void}){return <Card><CardHeader><div><CardTitle className="text-xl">سجل الرسائل</CardTitle><CardDescription className="mt-1">نتيجة كل إرسال ومعدلات الوصول والقراءة.</CardDescription></div></CardHeader><CardContent>{campaigns.length===0?<Empty text="لم تُنشأ أي رسائل بعد."/>:<div className="space-y-3">{campaigns.map(item=><div key={item.id} className="rounded-2xl border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{item.name}</h3><Badge variant={item.status==="COMPLETED"?"success":item.status==="FAILED"?"danger":item.status==="SCHEDULED"?"warning":"secondary"}>{statusLabels[item.status]}</Badge><Badge variant="outline">{purposes[item.purpose]}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{item.title}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.scheduledAt).toLocaleString("ar-SA")}</p></div>{item.status==="SCHEDULED"&&<Button variant="destructive" onClick={()=>cancel(item)}><XCircle/>إلغاء الجدولة</Button>}</div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric value={item.recipientCount} label="المستلمون"/><Metric value={item.inAppDeliveredCount} label="وصل داخل النظام"/><Metric value={item.readCount} label="تمت قراءته"/><Metric value={item.skippedCount} label="تعذر وصوله"/></div>{item.failureReason&&<p className="mt-3 rounded-xl bg-red-500/10 p-3 text-xs text-red-600">{item.failureReason}</p>}</div>)}</div>}</CardContent></Card>}
function TemplateList({templates,edit,canManage}:{templates:Template[];edit:(value:Template|"NEW")=>void;canManage:boolean}){return <Card><CardHeader><div><CardTitle className="text-xl">الرسائل المحفوظة</CardTitle><CardDescription className="mt-1">قوالب جاهزة للاستخدام المتكرر مع إمكانية تعديلها أو إيقافها.</CardDescription></div>{canManage&&<Button onClick={()=>edit("NEW")}><CopyPlus/>حفظ رسالة</Button>}</CardHeader><CardContent>{templates.length===0?<Empty text="لا توجد رسائل محفوظة."/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates.map(item=><button key={item.id} disabled={!canManage} onClick={()=>edit(item)} className="rounded-2xl border p-4 text-right transition enabled:hover:border-primary enabled:hover:bg-primary/5 disabled:cursor-default"><div className="flex items-center justify-between gap-2"><h3 className="font-black">{item.name}</h3><Badge variant={item.status==="ACTIVE"?"success":"secondary"}>{item.status==="ACTIVE"?"متاح":"متوقف"}</Badge></div><p className="mt-3 text-sm font-bold">{item.title}</p><p className="mt-2 line-clamp-3 text-xs leading-6 text-muted-foreground">{item.body}</p></button>)}</div>}</CardContent></Card>}

function TemplateDialog({value,organizationId,branchId,close,saved}:{value:Template|"NEW";organizationId:string;branchId?:string;close:()=>void;saved:()=>void}){const toast=useToast();const current=value==="NEW"?undefined:value;const[name,setName]=useState(current?.name??""),[purpose,setPurpose]=useState<Purpose>(current?.purpose??"ANNOUNCEMENT"),[title,setTitle]=useState(current?.title??""),[body,setBody]=useState(current?.body??""),[status,setStatus]=useState<"ACTIVE"|"INACTIVE">(current?.status??"ACTIVE"),[busy,setBusy]=useState(false);async function submit(){if(!name.trim()||!title.trim()||!body.trim()){toast.warning("أكمل بيانات الرسالة المحفوظة.");return}setBusy(true);try{await apiRequest(`/organizations/${organizationId}/communication-templates${current?`/${current.id}`:""}`,{method:current?"PATCH":"POST",body:JSON.stringify({...(branchId?{branchId}:{}),name,purpose,title,body,...(current?{status,expectedVersion:current.version}:{})})});toast.success(current?"تم تحديث الرسالة المحفوظة.":"تم حفظ الرسالة لاستخدامها لاحقًا.");await saved()}catch(reason){toast.error(humanError(reason,"تعذر حفظ الرسالة."))}finally{setBusy(false)}}return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><Card className="w-full max-w-2xl"><CardHeader><div><CardTitle>{current?"تعديل رسالة محفوظة":"حفظ رسالة متكررة"}</CardTitle><CardDescription className="mt-1">يمكن استدعاؤها لاحقًا وتعديل محتواها قبل الإرسال.</CardDescription></div><Button variant="ghost" size="icon" onClick={close}><XCircle/></Button></CardHeader><CardContent className="space-y-4"><Field label="اسم الرسالة"><Input className="h-11" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="الغرض"><select className={cn(inputClass,"w-full")} value={purpose} onChange={e=>setPurpose(e.target.value as Purpose)}>{Object.entries(purposes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="العنوان"><Input className="h-11" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="النص"><textarea className="min-h-36 w-full rounded-xl border bg-background p-3 text-sm leading-7" value={body} onChange={e=>setBody(e.target.value)}/></Field>{current&&<Field label="الحالة"><select className={cn(inputClass,"w-full")} value={status} onChange={e=>setStatus(e.target.value as "ACTIVE"|"INACTIVE")}><option value="ACTIVE">متاحة للاستخدام</option><option value="INACTIVE">متوقفة</option></select></Field>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={close}>إلغاء</Button><Button onClick={submit} disabled={busy}><Save/>{busy?"جارٍ الحفظ...":"حفظ"}</Button></div></CardContent></Card></div>}

function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-sm font-bold">{label}{hint&&<small className="font-normal text-muted-foreground">({hint})</small>}</span>{children}</label>}
function Choice({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={cn("min-h-11 rounded-xl border px-3 text-sm font-bold transition",active?"border-primary bg-primary text-primary-foreground":"bg-background hover:border-primary")}>{label}</button>}
function Metric({value,label}:{value:number;label:string}){return <div className="min-w-28 rounded-xl border bg-background/65 p-3"><p className="text-xl font-black">{value.toLocaleString("ar-SA")}</p><p className="mt-1 text-[11px] text-muted-foreground">{label}</p></div>}
function Empty({text}:{text:string}){return <div className="grid min-h-48 place-items-center rounded-2xl border border-dashed text-sm text-muted-foreground">{text}</div>}
function Loading(){return <div className="grid min-h-64 place-items-center"><span className="size-10 animate-spin rounded-full border-4 border-primary border-t-transparent"/></div>}
function list(value:unknown):SearchRow[]{if(Array.isArray(value))return value as SearchRow[];if(value&&typeof value==="object"&&"items" in value&&Array.isArray((value as {items:unknown}).items))return (value as {items:SearchRow[]}).items;return[]}
function audienceFilter(type:AudienceType,targetId:string,days:number,statuses:string[]){if(type==="SINGLE_MEMBER")return{memberId:targetId};if(type==="SINGLE_LEAD")return{leadId:targetId};if(type==="MEMBER_SEGMENT")return{memberStatus:"ACTIVE",subscriptionEndingWithinDays:Math.max(1,Math.min(365,days||7))};if(type==="LEAD_SEGMENT"||type==="ALL_LEADS")return{leadStatuses:statuses.length?statuses:["NEW","CONTACTED","QUALIFIED","TRIAL_SCHEDULED"]};return{memberStatus:"ACTIVE"}}
function validAudience(type:AudienceType,targetId:string){return !["SINGLE_MEMBER","SINGLE_LEAD"].includes(type)||Boolean(targetId)}
function localDateTime(date:Date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60_000).toISOString().slice(0,16)}
