"use client"

import { useEffect, useState } from "react"
import { CalendarClock, Loader2, Plus, RefreshCw, UserRoundSearch, Wifi } from "lucide-react"
import { ActionDialog } from "@/components/action-dialog"
import { useAppContext } from "@/components/app-context"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { apiRequest, createIdempotencyKey } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Row=Record<string,unknown>
const tabs=[{key:"leads",label:"العملاء المحتملون",icon:UserRoundSearch,permission:"crm.leads.read",fields:[["fullName","الاسم"],["phoneE164","الجوال"],["interestType","الاهتمام"],["nextFollowUpAt","المتابعة القادمة"],["status","الحالة"]]},{key:"followups",label:"المتابعات",icon:CalendarClock,permission:"crm.follow-ups.read",fields:[["leadName","العميل"],["channel","القناة"],["scheduledAt","الموعد"],["outcome","النتيجة"],["status","الحالة"]]},{key:"requests",label:"طلبات الموقع",icon:Wifi,permission:"online-requests.read",fields:[["requesterName","الاسم"],["requesterPhoneE164","الجوال"],["requestType","الطلب"],["createdAt","التاريخ"],["status","الحالة"]]}] as const
export function CrmWorkspace(){const context=useAppContext();const available=tabs.filter(tab=>context.canAccess([tab.permission]));const[active,setActive]=useState(available[0]?.key??"leads");const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[create,setCreate]=useState(false);const[busy,setBusy]=useState("");const tab=available.find(item=>item.key===active)??available[0]
 async function load(){if(!tab||!context.organizationId||!context.branchId)return;setLoading(true);setError("");try{const path=tab.key==="leads"?`/organizations/${context.organizationId}/crm/leads?branchId=${context.branchId}&limit=100`:tab.key==="followups"?`/organizations/${context.organizationId}/crm/follow-ups?branchId=${context.branchId}&limit=100`:`/organizations/${context.organizationId}/online-requests?branchId=${context.branchId}&limit=100`;const response=await apiRequest<unknown>(path);setRows(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل بيانات العملاء والمتابعات."))}finally{setLoading(false)}}useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[active,context.branchId,context.organizationId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function act(row:Row,action:string){const id=String(row.id??"");if(!id)return;setBusy(id);setError("");try{if(tab.key==="leads"){if(action==="FOLLOW_UP"){await apiRequest(`/organizations/${context.organizationId}/crm/leads/${id}/follow-ups`,{method:"POST",idempotencyKey:createIdempotencyKey(),body:JSON.stringify({assignedToUserAccountId:context.userAccountId,channel:"CALL",scheduledAt:tomorrowIso(),subject:"متابعة العميل المحتمل"})})}else{const body:Record<string,unknown>={status:action,expectedVersion:Number(row.version??1)};if(["LOST","DISQUALIFIED"].includes(action))body.reason="لم تكتمل فرصة البيع";await apiRequest(`/organizations/${context.organizationId}/crm/leads/${id}/transitions`,{method:"POST",body:JSON.stringify(body)})}}else if(tab.key==="followups"){const body=action==="COMPLETED"?{status:action,outcome:"OTHER",notes:"تمت المتابعة",expectedVersion:Number(row.version??1)}:{status:action,expectedVersion:Number(row.version??1)};await apiRequest(`/organizations/${context.organizationId}/crm/follow-ups/${id}/transitions`,{method:"POST",body:JSON.stringify(body)})}else{await apiRequest(`/organizations/${context.organizationId}/online-requests/${id}/transitions`,{method:"POST",body:JSON.stringify({branchId:context.branchId,status:action,expectedVersion:Number(row.version??1)})})}await load()}catch(reason){setError(humanError(reason,"تعذر تنفيذ إجراء المتابعة."))}finally{setBusy("")}}
 if(!tab)return <p className="text-sm text-muted-foreground">لا توجد مهام تجارية مخصصة لهذا الحساب.</p>;return <div className="fade-up"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">المبيعات والمتابعات</Badge><h1 className="mt-3 text-3xl font-black">العملاء المحتملون</h1><p className="mt-2 text-sm text-muted-foreground">من أول طلب تواصل حتى المتابعة وتحويل العميل إلى عضو.</p></div><div className="mr-auto flex gap-2">{active==="leads"&&context.canAccess(["crm.leads.manage"])&&<Button onClick={()=>setCreate(true)}><Plus/>إضافة عميل</Button>}<Button variant="outline" onClick={()=>void load()}><RefreshCw/>تحديث</Button></div></div><div className="mt-6 flex gap-2 overflow-x-auto">{available.map(item=><Button key={item.key} variant={item.key===tab.key?"default":"outline"} onClick={()=>setActive(item.key)}><item.icon/>{item.label}</Button>)}</div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}<Card className="mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-right"><thead className="bg-secondary/50"><tr>{tab.fields.map(field=><th key={field[0]} className="px-5 py-4 text-xs text-muted-foreground">{field[1]}</th>)}<th className="px-5 py-4 text-xs text-muted-foreground">الإجراء</th></tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={String(row.id??index)}>{tab.fields.map(field=><td key={field[0]} className="px-5 py-4 text-sm">{display(row[field[0]],field[0])}</td>)}<td className="px-5 py-3"><Actions tab={tab.key} row={row} busy={busy===String(row.id)} canManage={context.canAccess([tab.key==="leads"?"crm.leads.manage":tab.key==="followups"?"crm.follow-ups.manage":"online-requests.manage"])} onAction={value=>void act(row,value)}/></td></tr>)}</tbody></table>{loading?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:!rows.length&&!error?<p className="p-12 text-center text-sm text-muted-foreground">لا توجد سجلات في هذا القسم.</p>:null}</div></Card>{create&&<ActionDialog operationId="createCrmLead" organizationId={context.organizationId} branchId={context.branchId} onClose={()=>setCreate(false)} onSaved={()=>void load()}/>}</div>}
function Actions({tab,row,busy,canManage,onAction}:{tab:string;row:Row;busy:boolean;canManage:boolean;onAction:(value:string)=>void}){if(!canManage)return <span className="text-xs text-muted-foreground">عرض فقط</span>;const status=String(row.status??"");let actions:Array<[string,string]>=[];if(tab==="leads")actions=status==="NEW"?[["CONTACTED","تم التواصل"],["FOLLOW_UP","متابعة غدًا"]]:status==="CONTACTED"?[["QUALIFIED","مؤهل"],["LOST","غير مكتمل"],["FOLLOW_UP","متابعة غدًا"]]:status==="QUALIFIED"?[["TRIAL_SCHEDULED","جدولة تجربة"],["FOLLOW_UP","متابعة غدًا"]]:[];if(tab==="followups"&&status==="SCHEDULED")actions=[["COMPLETED","إكمال"],["MISSED","لم يرد"],["CANCELLED","إلغاء"]];if(tab==="requests"&&status==="PENDING")actions=[["APPROVED","اعتماد"],["REJECTED","رفض"]];return <div className="flex gap-2">{actions.map(([value,label])=><Button key={value} size="sm" variant={["LOST","REJECTED","CANCELLED"].includes(value)?"destructive":"outline"} disabled={busy} onClick={()=>onAction(value)}>{busy?<Loader2 className="animate-spin"/>:label}</Button>)}{!actions.length&&<span className="text-xs text-muted-foreground">لا إجراء متاح</span>}</div>}
function list(value:unknown):Row[]{return Array.isArray(value)?value as Row[]:value&&typeof value==="object"&&Array.isArray((value as {items?:Row[]}).items)?(value as {items:Row[]}).items:[]}
function display(value:unknown,key:string){if(value==null||value==="")return"—";if(typeof value==="string"&&key.endsWith("At")){const date=new Date(value);if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(date)}return({NEW:"جديد",CONTACTED:"تم التواصل",QUALIFIED:"مؤهل",TRIAL_SCHEDULED:"تجربة مجدولة",CONVERTED:"تحول إلى عضو",LOST:"فرصة غير مكتملة",SCHEDULED:"مجدولة",COMPLETED:"مكتملة",MISSED:"لم يرد",CANCELLED:"ملغاة",PENDING:"قيد المراجعة",APPROVED:"معتمدة",REJECTED:"مرفوضة",CALL:"اتصال",WHATSAPP:"واتساب",SMS:"رسالة نصية",EMAIL:"بريد إلكتروني",VISIT:"زيارة",GENERAL:"اهتمام عام",PACKAGE:"باقة",PERSONAL_TRAINING:"تدريب شخصي",MEAL_PLAN:"خطة غذائية"} as Record<string,string>)[String(value)]??String(value)}
function tomorrowIso(){const date=new Date();date.setDate(date.getDate()+1);return date.toISOString()}
