"use client"

import { useEffect, useMemo, useState } from "react"
import { Clock3, Loader2, LogIn, LogOut, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { apiRequest, createIdempotencyKey } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Employee={organizationId:string;employeeId:string;employeeNumber:string;name:string}
type Row=Record<string,unknown>
export function EmployeeSelfPanel({employee,branchId}:{employee:Employee;branchId:string}){const[shifts,setShifts]=useState<Row[]>([]);const[attendance,setAttendance]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const range=useMemo(()=>monthRange(),[])
 async function load(){setLoading(true);setError("");try{const query=`from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`;const [shiftResponse,attendanceResponse]=await Promise.all([apiRequest<unknown>(`/self/organizations/${employee.organizationId}/employee/shifts?${query}`),apiRequest<unknown>(`/self/organizations/${employee.organizationId}/employee/attendance?${query}`)]);setShifts(list(shiftResponse.data));setAttendance(list(attendanceResponse.data))}catch(reason){setError(humanError(reason,"تعذر تحميل جدول العمل."))}finally{setLoading(false)}}useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[employee.employeeId]) // eslint-disable-line react-hooks/exhaustive-deps
 const nextEvent=String(attendance[0]?.eventType??"")==="CLOCK_IN"?"CLOCK_OUT":"CLOCK_IN";async function record(){if(!branchId)return;setBusy(true);setError("");try{await apiRequest(`/self/organizations/${employee.organizationId}/employee/attendance`,{method:"POST",idempotencyKey:createIdempotencyKey(),body:JSON.stringify({branchId,eventType:nextEvent,occurredAt:new Date().toISOString()})});await load()}catch(reason){setError(humanError(reason,"تعذر تسجيل الحضور."))}finally{setBusy(false)}}
 return <Card className="mt-5"><CardContent className="p-5"><div className="flex flex-wrap items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-500/10 text-blue-600"><Clock3/></span><div><h2 className="font-black">دوامي ومناوباتي</h2><p className="mt-1 text-xs text-muted-foreground">{employee.name} · {employee.employeeNumber}</p></div><div className="mr-auto flex gap-2"><Button disabled={busy||!branchId} onClick={()=>void record()}>{busy?<Loader2 className="animate-spin"/>:nextEvent==="CLOCK_IN"?<LogIn/>:<LogOut/>}{nextEvent==="CLOCK_IN"?"تسجيل الحضور":"تسجيل الانصراف"}</Button><Button variant="outline" size="icon" onClick={()=>void load()} aria-label="تحديث"><RefreshCw/></Button></div></div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-xs text-red-600">{error}</p>}{loading?<div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:<div className="mt-5 grid gap-4 lg:grid-cols-2"><div><h3 className="text-xs font-black">المناوبات القادمة</h3><div className="mt-2 space-y-2">{shifts.slice(0,6).map((row,index)=><p key={String(row.id??index)} className="rounded-xl bg-secondary/50 p-3 text-xs">{format(row.startsAt)} — {format(row.endsAt)}</p>)}{!shifts.length&&<p className="text-xs text-muted-foreground">لا توجد مناوبات في الفترة المحددة.</p>}</div></div><div><h3 className="text-xs font-black">آخر حركات الحضور</h3><div className="mt-2 space-y-2">{attendance.slice(0,6).map((row,index)=><p key={String(row.id??index)} className="rounded-xl bg-secondary/50 p-3 text-xs">{row.eventType==="CLOCK_IN"?"دخول":"انصراف"} · {format(row.occurredAt)}</p>)}{!attendance.length&&<p className="text-xs text-muted-foreground">لم تسجل حركات حضور بعد.</p>}</div></div></div>}</CardContent></Card>}
function list(value:unknown):Row[]{return Array.isArray(value)?value as Row[]:value&&typeof value==="object"&&Array.isArray((value as {items?:Row[]}).items)?(value as {items:Row[]}).items:[]}
function format(value:unknown){const date=new Date(String(value));return Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(date)}
function monthRange(){const from=new Date();from.setDate(from.getDate()-30);const to=new Date();to.setDate(to.getDate()+30);return{from:from.toISOString(),to:to.toISOString()}}
