"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { AlertCircle, CheckCircle2, Clock3, Inbox, Lightbulb, Loader2, MessageCircleMore, Plus, RefreshCw, Search, Send, X } from "lucide-react"
import { useAppContext } from "@/components/app-context"
import type { PortalMember } from "@/components/member-portal"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useToast } from "@/components/toast-provider"
import { apiRequest } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"
import { cn } from "@/lib/utils"

type TicketStatus="OPEN"|"IN_REVIEW"|"WAITING_FOR_MEMBER"|"RESOLVED"|"CLOSED"
type Ticket={id:string;caseNumber:string;caseType:"COMPLAINT"|"SUGGESTION";subject:string;description:string;priority:"LOW"|"NORMAL"|"HIGH"|"URGENT";status:TicketStatus;branchId?:string;branchName?:string;memberId?:string;memberName?:string;memberNumber?:string;lastMessageAt:string;unreadForStaff?:boolean;unreadForMember?:boolean;messageCount?:number;version:number;resolution?:string;messages?:TicketMessage[]}
type TicketMessage={id:string;senderType:"MEMBER"|"STAFF";senderName?:string;body:string;createdAt:string}
type Branch={id:string;name:string;nameAr?:string}

const statusLabels:Record<TicketStatus,string>={OPEN:"جديدة",IN_REVIEW:"قيد المتابعة",WAITING_FOR_MEMBER:"بانتظار رد العضو",RESOLVED:"تم الحل",CLOSED:"مغلقة"}
const priorityLabels={LOW:"منخفضة",NORMAL:"عادية",HIGH:"مرتفعة",URGENT:"عاجلة"} as const
const typeLabels={COMPLAINT:"شكوى",SUGGESTION:"اقتراح"} as const

export function StaffFeedbackWorkspace(){
 const context=useAppContext(),toast=useToast();const canReply=context.canAccess(["feedback.reply"])
 const [tickets,setTickets]=useState<Ticket[]>([]),[selectedId,setSelectedId]=useState(""),[detail,setDetail]=useState<Ticket>(),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("")
 const [query,setQuery]=useState(""),[status,setStatus]=useState(""),[caseType,setCaseType]=useState(""),[branchId,setBranchId]=useState(context.branchId),[reply,setReply]=useState(""),[resolution,setResolution]=useState("")
 useEffect(()=>{const frame=requestAnimationFrame(()=>setBranchId(context.branchId));return()=>cancelAnimationFrame(frame)},[context.branchId])
 const load=useCallback(async()=>{if(!context.organizationId||!branchId)return;setLoading(true);setError("");try{const params=new URLSearchParams({branchId,limit:"200"});if(query.trim())params.set("q",query.trim());if(status)params.set("status",status);if(caseType)params.set("caseType",caseType);const response=await apiRequest<Ticket[]>(`/organizations/${context.organizationId}/feedback-cases?${params}`);const rows=Array.isArray(response.data)?response.data:[];setTickets(rows);setSelectedId(current=>rows.some(row=>row.id===current)?current:rows[0]?.id??"")}catch(reason){setError(humanError(reason,"تعذر تحميل صندوق الشكاوى والاقتراحات."))}finally{setLoading(false)}},[branchId,caseType,context.organizationId,query,status])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),query?350:0);return()=>window.clearTimeout(timer)},[load,query])
 const loadDetail=useCallback(async(id:string)=>{if(!id||!context.organizationId)return;setDetailLoading(true);try{const response=await apiRequest<Ticket>(`/organizations/${context.organizationId}/feedback-cases/${id}`);setDetail(response.data);setResolution(response.data.resolution??"");setTickets(rows=>rows.map(row=>row.id===id?{...row,unreadForStaff:false}:row));void apiRequest(`/organizations/${context.organizationId}/feedback-cases/${id}/read`,{method:"POST",body:"{}"}).catch(()=>undefined)}catch(reason){setError(humanError(reason,"تعذر فتح المحادثة."))}finally{setDetailLoading(false)}},[context.organizationId])
 useEffect(()=>{const frame=requestAnimationFrame(()=>{if(selectedId)void loadDetail(selectedId);else setDetail(undefined)});return()=>cancelAnimationFrame(frame)},[loadDetail,selectedId])
 async function sendReply(){if(!detail||reply.trim().length===0)return;setBusy(true);try{await apiRequest(`/organizations/${context.organizationId}/feedback-cases/${detail.id}/messages`,{method:"POST",body:JSON.stringify({body:reply.trim()})});setReply("");toast.success("تم إرسال الرد للعضو وأصبحت التذكرة بانتظار رده.");await Promise.all([load(),loadDetail(detail.id)])}catch(reason){toast.error(humanError(reason,"تعذر إرسال الرد."))}finally{setBusy(false)}}
 async function transition(next:TicketStatus){if(!detail)return;setBusy(true);try{await apiRequest(`/organizations/${context.organizationId}/feedback-cases/${detail.id}/transitions`,{method:"POST",body:JSON.stringify({status:next,expectedVersion:detail.version,...(resolution.trim().length>=3?{resolution:resolution.trim()}:{})})});toast.success(next==="CLOSED"?"تم إغلاق التذكرة.":next==="RESOLVED"?"تم تسجيل حل التذكرة.":"تم تحديث حالة التذكرة.");await Promise.all([load(),loadDetail(detail.id)])}catch(reason){toast.error(humanError(reason,"تعذر تحديث حالة التذكرة."))}finally{setBusy(false)}}
 const counts=useMemo(()=>({all:tickets.length,unread:tickets.filter(t=>t.unreadForStaff).length,active:tickets.filter(t=>!["RESOLVED","CLOSED"].includes(t.status)).length,resolved:tickets.filter(t=>["RESOLVED","CLOSED"].includes(t.status)).length}),[tickets])
 return <div className="fade-up"><PageHeading eyebrow="خدمة الأعضاء" title="الشكاوى والاقتراحات" description="صندوق متابعة موحّد؛ افتح التذكرة، راجع كامل المحادثة، ورد على العضو حتى اكتمال الحل." action={<Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={cn(loading&&"animate-spin")}/>تحديث</Button>}/>
  <MetricRow values={[{label:"إجمالي التذاكر",value:counts.all,icon:Inbox},{label:"تحتاج انتباهك",value:counts.unread,icon:MessageCircleMore},{label:"قيد المتابعة",value:counts.active,icon:Clock3},{label:"مكتملة",value:counts.resolved,icon:CheckCircle2}]}/>
  <Card className="mt-5 overflow-hidden"><div className="grid min-h-[650px] lg:grid-cols-[390px_1fr]"><section className="border-b lg:border-b-0 lg:border-l"><div className="space-y-3 border-b p-4"><div className="relative"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pr-10" placeholder="ابحث بالرقم أو العضو أو الموضوع…"/></div><div className="grid grid-cols-3 gap-2"><Select value={branchId} onChange={setBranchId} aria="الفرع"><option value="" disabled>الفرع</option>{context.branches.map(branch=><option key={branch.id} value={branch.id}>{branch.nameAr??branch.name}</option>)}</Select><Select value={status} onChange={setStatus} aria="الحالة"><option value="">كل الحالات</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select><Select value={caseType} onChange={setCaseType} aria="النوع"><option value="">كل الأنواع</option><option value="COMPLAINT">شكاوى</option><option value="SUGGESTION">اقتراحات</option></Select></div></div><TicketList tickets={tickets} selectedId={selectedId} onSelect={setSelectedId} unreadKey="unreadForStaff" loading={loading} error={error}/></section>
   <TicketConversation ticket={detail} loading={detailLoading} audience="staff" reply={reply} onReplyChange={setReply} onSend={()=>void sendReply()} busy={busy} canReply={canReply} actions={canReply&&detail?<StaffActions ticket={detail} resolution={resolution} setResolution={setResolution} busy={busy} transition={next=>void transition(next)}/>:undefined}/></div></Card>
 </div>
}

export function MemberFeedbackCenter({member}:{member:PortalMember}){
 const toast=useToast();const[tickets,setTickets]=useState<Ticket[]>([]),[selectedId,setSelectedId]=useState(""),[detail,setDetail]=useState<Ticket>(),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[createOpen,setCreateOpen]=useState(false),[reply,setReply]=useState("")
 const base=`/self/organizations/${member.organizationId}/members/${member.memberId}/feedback-cases`
 const load=useCallback(async()=>{setLoading(true);try{const response=await apiRequest<Ticket[]>(`${base}?limit=100`);const rows=Array.isArray(response.data)?response.data:[];setTickets(rows);setSelectedId(current=>rows.some(row=>row.id===current)?current:rows[0]?.id??"")}catch(reason){toast.error(humanError(reason,"تعذر تحميل تذاكرك."))}finally{setLoading(false)}},[base,toast])
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[load])
 const loadDetail=useCallback(async(id:string)=>{if(!id)return;setDetailLoading(true);try{const response=await apiRequest<Ticket>(`${base}/${id}`);setDetail(response.data);setTickets(rows=>rows.map(row=>row.id===id?{...row,unreadForMember:false}:row));void apiRequest(`${base}/${id}/read`,{method:"POST",body:"{}"}).catch(()=>undefined)}catch(reason){toast.error(humanError(reason,"تعذر فتح التذكرة."))}finally{setDetailLoading(false)}},[base,toast])
 useEffect(()=>{const frame=requestAnimationFrame(()=>{if(selectedId)void loadDetail(selectedId);else setDetail(undefined)});return()=>cancelAnimationFrame(frame)},[loadDetail,selectedId])
 async function sendReply(){if(!detail||!reply.trim())return;setBusy(true);try{await apiRequest(`${base}/${detail.id}/messages`,{method:"POST",body:JSON.stringify({body:reply.trim()})});setReply("");toast.success("تم إرسال رسالتك إلى فريق النادي.");await Promise.all([load(),loadDetail(detail.id)])}catch(reason){toast.error(humanError(reason,"تعذر إرسال الرسالة."))}finally{setBusy(false)}}
 async function transition(status:"OPEN"|"CLOSED"){if(!detail)return;setBusy(true);try{await apiRequest(`${base}/${detail.id}/transitions`,{method:"POST",body:JSON.stringify({status,expectedVersion:detail.version})});toast.success(status==="CLOSED"?"تم إغلاق التذكرة. شكرًا لتأكيد اكتمال المتابعة.":"تمت إعادة فتح التذكرة.");await Promise.all([load(),loadDetail(detail.id)])}catch(reason){toast.error(humanError(reason,"تعذر تحديث التذكرة."))}finally{setBusy(false)}}
 const counts=useMemo(()=>({all:tickets.length,unread:tickets.filter(t=>t.unreadForMember).length,open:tickets.filter(t=>!["RESOLVED","CLOSED"].includes(t.status)).length}),[tickets])
 return <div><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">تذاكر الدعم</h2><p className="mt-1 text-xs leading-6 text-muted-foreground">قدّم شكوى أو اقتراحًا وتابع الردود مع فريق النادي في محادثة واحدة واضحة.</p></div><Button className="sm:mr-auto" onClick={()=>setCreateOpen(true)}><Plus/>تذكرة جديدة</Button></div>
  <MetricRow values={[{label:"كل التذاكر",value:counts.all,icon:Inbox},{label:"ردود جديدة",value:counts.unread,icon:MessageCircleMore},{label:"قيد المتابعة",value:counts.open,icon:Clock3}]}/>
  <Card className="mt-5 overflow-hidden"><div className="grid min-h-[620px] lg:grid-cols-[360px_1fr]"><section className="border-b lg:border-b-0 lg:border-l"><TicketList tickets={tickets} selectedId={selectedId} onSelect={setSelectedId} unreadKey="unreadForMember" loading={loading}/></section><TicketConversation ticket={detail} loading={detailLoading} audience="member" reply={reply} onReplyChange={setReply} onSend={()=>void sendReply()} busy={busy} canReply={Boolean(detail&&detail.status!=="CLOSED")} actions={detail?<MemberActions ticket={detail} busy={busy} transition={status=>void transition(status)}/>:undefined}/></div></Card>
  {createOpen&&<CreateTicketDialog member={member} onClose={()=>setCreateOpen(false)} onSaved={async id=>{setCreateOpen(false);await load();setSelectedId(id)}}/>}
 </div>
}

function TicketList({tickets,selectedId,onSelect,unreadKey,loading,error}:{tickets:Ticket[];selectedId:string;onSelect:(id:string)=>void;unreadKey:"unreadForStaff"|"unreadForMember";loading:boolean;error?:string}){if(loading)return <div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-primary"/></div>;if(error)return <p role="alert" className="m-4 rounded-xl bg-red-500/10 p-4 text-xs leading-6 text-red-600">{error}</p>;if(!tickets.length)return <div className="grid min-h-72 place-items-center p-8 text-center"><div><Inbox className="mx-auto size-10 text-muted-foreground/35"/><p className="mt-3 text-sm font-black">لا توجد تذاكر هنا</p><p className="mt-1 text-xs text-muted-foreground">ستظهر المحادثات الجديدة في هذا الصندوق.</p></div></div>;return <div className="max-h-[650px] divide-y overflow-y-auto">{tickets.map(ticket=><button type="button" key={ticket.id} onClick={()=>onSelect(ticket.id)} className={cn("block w-full p-4 text-right transition hover:bg-secondary/60",selectedId===ticket.id&&"bg-primary/[.08]")}><div className="flex items-center gap-2"><span className={cn("size-2 shrink-0 rounded-full",ticket[unreadKey]?"bg-primary":"bg-transparent")}/><span dir="ltr" className="text-[10px] font-black tracking-wide text-primary">{ticket.caseNumber}</span><StatusBadge status={ticket.status}/></div><h3 className="mt-2 line-clamp-1 text-sm font-black">{ticket.subject}</h3>{ticket.memberName&&<p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{ticket.memberName} · <span dir="ltr">{ticket.memberNumber}</span></p>}<div className="mt-2 flex items-center gap-2 text-[10px] text-muted-foreground"><span>{typeLabels[ticket.caseType]}</span><span>•</span><span>{formatDate(ticket.lastMessageAt)}</span><span className="mr-auto">{ticket.messageCount??0} رسائل</span></div></button>)}</div>}

function TicketConversation({ticket,loading,audience,reply,onReplyChange,onSend,busy,canReply,actions}:{ticket?:Ticket;loading:boolean;audience:"member"|"staff";reply:string;onReplyChange:(value:string)=>void;onSend:()=>void;busy:boolean;canReply:boolean;actions?:React.ReactNode}){if(loading)return <div className="grid min-h-96 place-items-center"><Loader2 className="animate-spin text-primary"/></div>;if(!ticket)return <div className="grid min-h-96 place-items-center p-8 text-center"><div><MessageCircleMore className="mx-auto size-12 text-muted-foreground/30"/><h2 className="mt-4 font-black">اختر تذكرة لعرض المحادثة</h2><p className="mt-2 text-xs text-muted-foreground">ستظهر الرسائل والإجراءات المتاحة هنا.</p></div></div>;return <section className="flex min-h-[620px] min-w-0 flex-col"><header className="border-b p-5"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span dir="ltr" className="text-xs font-black text-primary">{ticket.caseNumber}</span><StatusBadge status={ticket.status}/><Badge variant="outline">{typeLabels[ticket.caseType]}</Badge><Badge variant="outline">أولوية {priorityLabels[ticket.priority]}</Badge></div><h2 className="mt-3 text-xl font-black">{ticket.subject}</h2><p className="mt-2 text-xs text-muted-foreground">{ticket.branchName??"النادي"}{ticket.memberName?` · ${ticket.memberName} · ${ticket.memberNumber}`:""}</p></div>{actions}</div></header><div className="flex-1 space-y-4 overflow-y-auto bg-secondary/15 p-4 sm:p-6">{ticket.messages?.map(message=><MessageBubble key={message.id} message={message} own={audience==="member"?message.senderType==="MEMBER":message.senderType==="STAFF"}/>)}</div><footer className="border-t bg-card p-4">{ticket.status==="CLOSED"?<p className="rounded-xl bg-secondary p-4 text-center text-xs font-bold text-muted-foreground">هذه التذكرة مغلقة. يمكنك إعادة فتحها إذا احتجت متابعة جديدة لنفس الموضوع.</p>:canReply?<div><label className="text-xs font-black">اكتب ردك</label><div className="mt-2 flex items-end gap-2"><textarea value={reply} onChange={e=>onReplyChange(e.target.value)} rows={3} maxLength={5000} placeholder={audience==="staff"?"اكتب ردًا واضحًا يشرح الخطوة التالية للعضو…":"اكتب رسالتك أو أضف تفاصيل تساعد فريق النادي…"} className="min-h-20 flex-1 resize-none rounded-xl border bg-background p-3 text-sm leading-6 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15"/><Button size="icon" className="size-12" disabled={busy||!reply.trim()} onClick={onSend} aria-label="إرسال الرد">{busy?<Loader2 className="animate-spin"/>:<Send/>}</Button></div></div>:<p className="rounded-xl bg-secondary p-4 text-center text-xs font-bold text-muted-foreground">لديك صلاحية الاطلاع فقط؛ الرد وتغيير الحالة يحتاجان صلاحية «الرد على الشكاوى والاقتراحات».</p>}</footer></section>}

function MessageBubble({message,own}:{message:TicketMessage;own:boolean}){return <article className={cn("flex",own?"justify-start":"justify-end")}><div className={cn("max-w-[85%] rounded-2xl px-4 py-3 shadow-sm",own?"rounded-tr-sm bg-primary text-primary-foreground":"rounded-tl-sm border bg-card")}><div className="flex items-center gap-2 text-[10px] font-bold opacity-70"><span>{message.senderName??(message.senderType==="MEMBER"?"العضو":"فريق النادي")}</span><span>•</span><time>{formatDate(message.createdAt)}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{message.body}</p></div></article>}

function StaffActions({ticket,resolution,setResolution,busy,transition}:{ticket:Ticket;resolution:string;setResolution:(value:string)=>void;busy:boolean;transition:(status:TicketStatus)=>void}){return <div className="w-full space-y-2 sm:w-auto"><div className="flex flex-wrap gap-2">{ticket.status==="OPEN"&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>transition("IN_REVIEW")}>بدء المتابعة</Button>}{ticket.status==="WAITING_FOR_MEMBER"&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>transition("IN_REVIEW")}>استئناف المتابعة</Button>}{ticket.status==="RESOLVED"&&<Button size="sm" disabled={busy} onClick={()=>transition("CLOSED")}>إغلاق</Button>}{ticket.status==="CLOSED"&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>transition("OPEN")}>إعادة فتح</Button>}{!["RESOLVED","CLOSED"].includes(ticket.status)&&<Button size="sm" disabled={busy} onClick={()=>transition("RESOLVED")}><CheckCircle2/>تم الحل</Button>}</div>{!["CLOSED"].includes(ticket.status)&&<Input value={resolution} onChange={e=>setResolution(e.target.value)} className="h-9 text-xs" placeholder="ملخص الحل (اختياري)"/>}</div>}
function MemberActions({ticket,busy,transition}:{ticket:Ticket;busy:boolean;transition:(status:"OPEN"|"CLOSED")=>void}){if(ticket.status==="CLOSED")return <Button size="sm" variant="outline" disabled={busy} onClick={()=>transition("OPEN")}>إعادة فتح التذكرة</Button>;return <Button size="sm" variant="outline" disabled={busy} onClick={()=>transition("CLOSED")}><CheckCircle2/>تم حل الموضوع</Button>}

function CreateTicketDialog({member,onClose,onSaved}:{member:PortalMember;onClose:()=>void;onSaved:(id:string)=>void}){const toast=useToast();const[branches,setBranches]=useState<Branch[]>([]),[branchId,setBranchId]=useState(member.registrationBranchId),[caseType,setCaseType]=useState<"COMPLAINT"|"SUGGESTION">("COMPLAINT"),[priority,setPriority]=useState<"LOW"|"NORMAL"|"HIGH"|"URGENT">("NORMAL"),[subject,setSubject]=useState(""),[description,setDescription]=useState(""),[saving,setSaving]=useState(false)
 useEffect(()=>{void apiRequest<Branch[]>(`/self/organizations/${member.organizationId}/branches`).then(r=>{const rows=Array.isArray(r.data)?r.data:[];setBranches(rows);setBranchId(current=>rows.some(b=>b.id===current)?current:rows[0]?.id??member.registrationBranchId)}).catch(()=>undefined)},[member.organizationId,member.registrationBranchId])
 async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);try{const response=await apiRequest<Ticket>(`/self/organizations/${member.organizationId}/members/${member.memberId}/feedback-cases`,{method:"POST",body:JSON.stringify({branchId,caseType,subject:subject.trim(),description:description.trim(),priority})});toast.success(`تم إنشاء التذكرة ${response.data.caseNumber}.`);onSaved(response.data.id)}catch(reason){toast.error(humanError(reason,"تعذر إنشاء التذكرة."))}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-[90] grid place-items-end bg-black/65 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-labelledby="new-ticket-title" className="max-h-[94vh] w-full overflow-y-auto rounded-t-3xl border bg-card shadow-2xl sm:max-w-2xl sm:rounded-3xl"><header className="flex items-start gap-4 border-b p-5"><span className="grid size-11 place-items-center rounded-2xl bg-primary/15 text-primary">{caseType==="COMPLAINT"?<AlertCircle/>:<Lightbulb/>}</span><div><Badge variant="outline">تذكرة دعم جديدة</Badge><h2 id="new-ticket-title" className="mt-2 text-xl font-black">كيف يمكننا مساعدتك؟</h2><p className="mt-1 text-xs leading-6 text-muted-foreground">اختر النوع والفرع، واشرح الموضوع بوضوح. ستتابع كل الردود من هذه الصفحة.</p></div><Button className="mr-auto" variant="ghost" size="icon" onClick={onClose} aria-label="إغلاق"><X/></Button></header><form onSubmit={submit} className="space-y-5 p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="نوع التذكرة"><Select value={caseType} onChange={value=>setCaseType(value as typeof caseType)} aria="نوع التذكرة"><option value="COMPLAINT">شكوى تحتاج معالجة</option><option value="SUGGESTION">اقتراح لتطوير الخدمة</option></Select></Field><Field label="الفرع المرتبط"><Select value={branchId} onChange={setBranchId} aria="الفرع">{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.nameAr??branch.name}</option>)}</Select></Field><Field label="الأولوية"><Select value={priority} onChange={value=>setPriority(value as typeof priority)} aria="الأولوية"><option value="LOW">منخفضة</option><option value="NORMAL">عادية</option><option value="HIGH">مرتفعة</option><option value="URGENT">عاجلة — تعطل خدمة أساسية</option></Select></Field><Field label="عنوان مختصر"><Input required minLength={3} maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: مشكلة في حجز الحصة"/></Field></div><Field label="تفاصيل الموضوع"><textarea required minLength={3} maxLength={5000} rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="اشرح ما حدث، ومتى حدث، وما النتيجة التي تتوقعها…" className="w-full resize-none rounded-xl border bg-background p-3 text-sm leading-7 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15"/></Field><div className="flex flex-col-reverse gap-2 border-t pt-5 sm:flex-row"><Button type="button" variant="outline" onClick={onClose}>إلغاء</Button><Button type="submit" className="sm:mr-auto" disabled={saving||!branchId||subject.trim().length<3||description.trim().length<3}>{saving?<Loader2 className="animate-spin"/>:<Send/>}إرسال التذكرة</Button></div></form></section></div>}

function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action:React.ReactNode}){return <div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">{eyebrow}</Badge><h1 className="mt-3 text-3xl font-black">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-muted-foreground">{description}</p></div><div className="sm:mr-auto">{action}</div></div>}
function MetricRow({values}:{values:Array<{label:string;value:number;icon:typeof Inbox}>}){return <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{values.map(value=><Card key={value.label}><CardContent className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><value.icon className="size-5"/></span><div><p className="text-[11px] text-muted-foreground">{value.label}</p><p className="mt-1 text-xl font-black">{value.value}</p></div></CardContent></Card>)}</div>}
function StatusBadge({status}:{status:TicketStatus}){return <span className={cn("mr-auto rounded-full px-2 py-1 text-[9px] font-black",status==="OPEN"&&"bg-blue-500/10 text-blue-600",status==="IN_REVIEW"&&"bg-violet-500/10 text-violet-600",status==="WAITING_FOR_MEMBER"&&"bg-amber-500/10 text-amber-700",status==="RESOLVED"&&"bg-emerald-500/10 text-emerald-600",status==="CLOSED"&&"bg-secondary text-muted-foreground")}>{statusLabels[status]}</span>}
function Select({value,onChange,aria,children}:{value:string;onChange:(value:string)=>void;aria:string;children:React.ReactNode}){return <select aria-label={aria} value={value} onChange={e=>onChange(e.target.value)} className="h-10 min-w-0 rounded-xl border bg-background px-3 text-xs font-bold outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15">{children}</select>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-black">{label}</span>{children}</label>}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(date)}
