"use client"

import { useEffect, useMemo, useState } from "react"
import { BadgeDollarSign, CreditCard, HandCoins, Loader2, Plus, RefreshCw } from "lucide-react"
import { ActionDialog } from "@/components/action-dialog"
import { useAppContext } from "@/components/app-context"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { apiRequest } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Row=Record<string,unknown>
const definitions=[
 {key:"invoices",label:"الفواتير",icon:CreditCard,permission:"finance.invoices.read",path:(o:string,b:string)=>`/organizations/${o}/invoices?branchId=${b}&limit=100`,fields:[["invoiceNumber","الفاتورة"],["buyerName","العميل"],["grossMinor","الإجمالي"],["paidMinor","المدفوع"],["status","الحالة"]]},
 {key:"income",label:"الإيرادات الأخرى",icon:HandCoins,permission:"finance.other-income.read",path:(o:string,b:string,r:{from:string;to:string})=>`/organizations/${o}/other-income?branchId=${b}&from=${encodeURIComponent(r.from)}&to=${encodeURIComponent(r.to)}`,fields:[["categoryName","التصنيف"],["description","البيان"],["amountMinor","المبلغ"],["paymentMethodCode","الطريقة"],["status","الحالة"]]},
 {key:"commissions",label:"عمولات المدربين",icon:BadgeDollarSign,permission:"coaching.commissions.read",path:(o:string,b:string)=>`/organizations/${o}/trainer-commissions?branchId=${b}&limit=200`,fields:[["trainerName","المدرب"],["sourceType","المصدر"],["commissionAmountMinor","العمولة"],["occurredAt","التاريخ"],["status","الحالة"]]},
] as const

export function FinanceWorkspace(){const context=useAppContext();const available=definitions.filter(item=>context.canAccess([item.permission]));const[active,setActive]=useState(available[0]?.key??"");const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[dialog,setDialog]=useState<string>();const[busy,setBusy]=useState("");const range=useMemo(()=>monthRange(),[]);const tab=available.find(item=>item.key===active)??available[0]
 async function load(){if(!tab||!context.organizationId||!context.branchId)return;setLoading(true);setError("");try{const response=await apiRequest<unknown>(tab.path(context.organizationId,context.branchId,range));setRows(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل البيانات المالية."))}finally{setLoading(false)}}useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[active,context.branchId,context.organizationId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function transition(row:Row,status:string){const id=String(row.id??"");if(!id)return;setBusy(id);try{if(tab.key==="income"){const reason=window.prompt("سبب إلغاء القيد");if(!reason||reason.trim().length<3)return;await apiRequest(`/organizations/${context.organizationId}/other-income/${id}/voids`,{method:"POST",body:JSON.stringify({branchId:context.branchId,reason,expectedVersion:Number(row.version??1)})})}else if(tab.key==="commissions"){await apiRequest(`/organizations/${context.organizationId}/trainer-commissions/${id}/transitions`,{method:"POST",body:JSON.stringify({branchId:context.branchId,expectedStatus:String(row.status),status})})}await load()}catch(reason){setError(humanError(reason,"تعذر تنفيذ الحركة المالية."))}finally{setBusy("")}}
 if(!tab)return <p className="text-sm text-muted-foreground">لا توجد بيانات مالية مخصصة لهذا الحساب.</p>;const canCreate=tab.key==="invoices"?context.canAccess(["finance.payments.record"]):tab.key==="income"?context.canAccess(["finance.other-income.manage"]):false
 return <div className="fade-up"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">المالية</Badge><h1 className="mt-3 text-3xl font-black">السجلات المالية والعمولات</h1><p className="mt-2 text-sm text-muted-foreground">كل قيمة هنا مقروءة من قاعدة البيانات ومقيدة بنطاق الفرع الحالي.</p></div><div className="mr-auto flex gap-2">{canCreate&&<Button onClick={()=>setDialog(tab.key==="invoices"?"recordPayment":"recordOtherIncome")}><Plus/>{tab.key==="invoices"?"تسجيل دفعة":"تسجيل إيراد"}</Button>}<Button variant="outline" onClick={()=>void load()}><RefreshCw/>تحديث</Button></div></div><div className="mt-6 flex gap-2 overflow-x-auto">{available.map(item=><Button key={item.key} variant={item.key===tab.key?"default":"outline"} onClick={()=>setActive(item.key)}><item.icon/>{item.label}</Button>)}</div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}<Card className="mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right"><thead className="bg-secondary/50"><tr>{tab.fields.map(field=><th key={field[0]} className="px-5 py-4 text-xs text-muted-foreground">{field[1]}</th>)}<th className="px-5 py-4 text-xs text-muted-foreground">الإجراء</th></tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={String(row.id??index)}>{tab.fields.map(field=><td key={field[0]} className="px-5 py-4 text-sm">{display(row[field[0]]??fallback(row,field[0]),field[0])}</td>)}<td className="px-5 py-3"><FinanceActions tab={tab.key} row={row} busy={busy===String(row.id)} canManage={tab.key==="income"?context.canAccess(["finance.other-income.manage"]):context.canAccess(["coaching.commissions.manage"])} onAction={value=>void transition(row,value)}/></td></tr>)}</tbody></table>{loading?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:!rows.length&&!error?<p className="p-12 text-center text-sm text-muted-foreground">لا توجد سجلات في الفترة الحالية.</p>:null}</div></Card>{dialog&&<ActionDialog operationId={dialog} organizationId={context.organizationId} branchId={context.branchId} onClose={()=>setDialog(undefined)} onSaved={()=>void load()}/>}</div>}

function FinanceActions({tab,row,busy,canManage,onAction}:{tab:string;row:Row;busy:boolean;canManage:boolean;onAction:(value:string)=>void}){if(!canManage||tab==="invoices")return <span className="text-xs text-muted-foreground">عرض فقط</span>;const status=String(row.status??"");const actions=tab==="income"&&status==="RECORDED"?[["VOIDED","إلغاء القيد"]]:tab==="commissions"&&status==="ACCRUED"?[["APPROVED","اعتماد"],["VOIDED","إلغاء"]]:tab==="commissions"&&status==="APPROVED"?[["PAID","تسجيل السداد"]]:[];return <div className="flex gap-2">{actions.map(([value,label])=><Button key={value} size="sm" variant={value==="VOIDED"?"destructive":"outline"} disabled={busy} onClick={()=>onAction(value)}>{busy?<Loader2 className="animate-spin"/>:label}</Button>)}{!actions.length&&<span className="text-xs text-muted-foreground">لا إجراء متاح</span>}</div>}
function list(value:unknown):Row[]{if(Array.isArray(value))return value as Row[];if(value&&typeof value==="object"&&Array.isArray((value as {items?:unknown[]}).items))return (value as {items:Row[]}).items;return[]}
function fallback(row:Row,key:string){const aliases:Record<string,string[]>={invoiceNumber:["id"],buyerName:["memberName","memberId"],categoryName:["category_name","categoryCode"],trainerName:["displayName","trainerProfileId"]};for(const candidate of aliases[key]??[]){if(row[candidate]!=null)return row[candidate]}return undefined}
function display(value:unknown,key:string){if(value==null||value==="")return"—";if(key.toLowerCase().includes("minor"))return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(Number(value)/100);if(typeof value==="string"&&key.endsWith("At")){const date=new Date(value);if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeZone:"Asia/Riyadh"}).format(date)}const labels:Record<string,string>={RECORDED:"مسجل",VOIDED:"ملغى",ACCRUED:"مستحق",APPROVED:"معتمد",PAID:"مدفوع",CASH:"نقدي",CARD:"بطاقة",BANK_TRANSFER:"تحويل بنكي",GATEWAY:"بوابة دفع",WALLET:"محفظة",PERSONAL_TRAINING:"تدريب شخصي",SUBSCRIPTION_SALE:"بيع اشتراك",MANUAL_ADJUSTMENT:"تسوية يدوية"};return labels[String(value)]??String(value)}
function monthRange(){const to=new Date();to.setDate(to.getDate()+1);const from=new Date();from.setDate(from.getDate()-31);return{from:from.toISOString(),to:to.toISOString()}}
