"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { BadgeDollarSign, CreditCard, Eye, HandCoins, Loader2, Plus, RefreshCw, Search } from "lucide-react"
import { ActionDialog } from "@/components/action-dialog"
import { useAppContext } from "@/components/app-context"
import { Badge } from "@/components/ui/badge"
import { Button, buttonVariants } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { apiRequest, createIdempotencyKey } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Row=Record<string,unknown>
const definitions=[
 {key:"invoices",label:"الفواتير",icon:CreditCard,permission:"finance.invoices.read",path:(o:string,b:string)=>`/organizations/${o}/invoices?branchId=${b}&limit=100`,fields:[["invoiceNumber","الفاتورة"],["buyerName","العميل"],["grossMinor","الإجمالي"],["paidMinor","المدفوع"],["status","الحالة"]]},
 {key:"payments",label:"المدفوعات",icon:BadgeDollarSign,permission:"finance.payments.read",path:(o:string,b:string)=>`/organizations/${o}/payments?branchId=${b}&limit=100`,fields:[["externalReference","المرجع"],["paymentMethodCode","الطريقة"],["amountMinor","المبلغ"],["refundedMinor","المسترجع"],["status","الحالة"]]},
 {key:"refunds",label:"الاسترجاعات",icon:HandCoins,permission:"finance.payments.read",path:(o:string,b:string)=>`/organizations/${o}/refunds?branchId=${b}&limit=100`,fields:[["paymentMethodCode","طريقة الدفع الأصلية"],["amountMinor","المبلغ"],["reason","السبب"],["refundedAt","التاريخ"],["status","الحالة"]]},
 {key:"expenses",label:"المصروفات",icon:HandCoins,permission:"finance.expenses.read",path:(o:string,b:string)=>`/organizations/${o}/expenses?branchId=${b}&limit=100`,fields:[["categoryName","التصنيف"],["description","البيان"],["amountMinor","المبلغ"],["approvalRequired","يتطلب اعتماد"],["status","الحالة"]]},
 {key:"income",label:"الإيرادات الأخرى",icon:HandCoins,permission:"finance.other-income.read",path:(o:string,b:string,r:{from:string;to:string})=>`/organizations/${o}/other-income?branchId=${b}&from=${encodeURIComponent(r.from)}&to=${encodeURIComponent(r.to)}`,fields:[["categoryName","التصنيف"],["description","البيان"],["amountMinor","المبلغ"],["paymentMethodCode","الطريقة"],["status","الحالة"]]},
 {key:"commissions",label:"عمولات المدربين",icon:BadgeDollarSign,permission:"coaching.commissions.read",path:(o:string,b:string)=>`/organizations/${o}/trainer-commissions?branchId=${b}&limit=200`,fields:[["trainerName","المدرب"],["sourceType","المصدر"],["commissionAmountMinor","العمولة"],["occurredAt","التاريخ"],["status","الحالة"]]},
] as const

export function FinanceWorkspace({initialSearch=""}:{initialSearch?:string}){const context=useAppContext();const available=definitions.filter(item=>context.canAccess([item.permission]));const[active,setActive]=useState(available[0]?.key??"");const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[dialog,setDialog]=useState<string>();const[busy,setBusy]=useState("");const[search,setSearch]=useState(initialSearch);const[databaseSearch,setDatabaseSearch]=useState(initialSearch.trim());const range=useMemo(()=>monthRange(),[]);const tab=available.find(item=>item.key===active)??available[0]
 useEffect(()=>{const timer=window.setTimeout(()=>setDatabaseSearch(search.trim()),300);return()=>window.clearTimeout(timer)},[search])
 async function load(){if(!tab||!context.organizationId||!context.branchId)return;setLoading(true);setError("");try{const target=new URL(tab.path(context.organizationId,context.branchId,range),"http://local");if(tab.key==="invoices"&&databaseSearch)target.searchParams.set("q",databaseSearch);const response=await apiRequest<unknown>(`${target.pathname}${target.search}`);setRows(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل البيانات المالية."))}finally{setLoading(false)}}useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[active,context.branchId,context.organizationId,databaseSearch]) // eslint-disable-line react-hooks/exhaustive-deps
 async function transition(row:Row,status:string){const id=String(row.id??"");if(!id)return;setBusy(id);try{if(tab.key==="income"){const reason=window.prompt("سبب إلغاء القيد");if(!reason||reason.trim().length<3)return;await apiRequest(`/organizations/${context.organizationId}/other-income/${id}/voids`,{method:"POST",body:JSON.stringify({branchId:context.branchId,reason,expectedVersion:Number(row.version??1)})})}else if(tab.key==="commissions"){await apiRequest(`/organizations/${context.organizationId}/trainer-commissions/${id}/transitions`,{method:"POST",body:JSON.stringify({branchId:context.branchId,expectedStatus:String(row.status),status})})}else if(tab.key==="payments"&&status==="REFUND"){const refundable=Math.max(0,Number(row.amountMinor??0)-Number(row.refundedMinor??0));const amount=window.prompt("المبلغ المراد استرجاعه بالريال",String(refundable/100));const reason=window.prompt("سبب الاسترجاع");if(!amount||!reason||reason.trim().length<3)return;let cashierShiftId:string|undefined;if(String(row.paymentMethodCode)==="CASH"){const shifts=await apiRequest<unknown>(`/organizations/${context.organizationId}/cashier-shifts?branchId=${context.branchId}&status=OPEN&limit=10`);cashierShiftId=list(shifts.data).find(item=>item.status==="OPEN")?.id as string|undefined;if(!cashierShiftId)throw new Error("افتح وردية صندوق قبل تنفيذ استرجاع نقدي.")}await apiRequest(`/organizations/${context.organizationId}/payments/${id}/refunds`,{method:"POST",idempotencyKey:createIdempotencyKey(),body:JSON.stringify({amountMinor:String(Math.round(Number(amount)*100)),reason,...(cashierShiftId?{cashierShiftId}:{})})})}else if(tab.key==="expenses"){const body:Row={branchId:context.branchId,expectedVersion:Number(row.version??1),action:status};if(status==="VOID"){const reason=window.prompt("سبب إلغاء المصروف");if(!reason||reason.trim().length<3)return;body.reason=reason}if(status==="PAY"){const method=(window.prompt("طريقة السداد: CASH أو CARD أو BANK_TRANSFER","BANK_TRANSFER")||"").toUpperCase();if(!["CASH","CARD","BANK_TRANSFER"].includes(method))throw new Error("طريقة السداد غير صحيحة.");body.method=method;if(method==="CASH"){const shifts=await apiRequest<unknown>(`/organizations/${context.organizationId}/cashier-shifts?branchId=${context.branchId}&status=OPEN&limit=10`);const open=list(shifts.data).find(item=>item.status==="OPEN");if(!open)throw new Error("افتح وردية صندوق قبل سداد مصروف نقدي.");body.cashierShiftId=open.id}}await apiRequest(`/organizations/${context.organizationId}/expenses/${id}/transitions`,{method:"POST",body:JSON.stringify(body)})}await load()}catch(reason){setError(humanError(reason,"تعذر تنفيذ الحركة المالية."))}finally{setBusy("")}}
 if(!tab)return <p className="text-sm text-muted-foreground">لا توجد بيانات مالية مخصصة لهذا الحساب.</p>;const canCreate=tab.key==="invoices"?context.canAccess(["finance.payments.record"]):tab.key==="income"?context.canAccess(["finance.other-income.manage"]):tab.key==="expenses"?context.canAccess(["finance.expenses.manage"]):false
 return <div className="fade-up"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">المالية</Badge><h1 className="mt-3 text-3xl font-black">السجلات المالية والعمولات</h1><p className="mt-2 text-sm text-muted-foreground">كل قيمة هنا مقروءة من قاعدة البيانات ومقيدة بنطاق الفرع الحالي.</p></div><div className="mr-auto flex gap-2">{canCreate&&<Button onClick={()=>setDialog(tab.key==="invoices"?"recordPayment":tab.key==="expenses"?"recordExpense":"recordOtherIncome")}><Plus/>{tab.key==="invoices"?"تسجيل دفعة":tab.key==="expenses"?"تسجيل مصروف":"تسجيل إيراد"}</Button>}<Button variant="outline" onClick={()=>void load()}><RefreshCw/>تحديث</Button></div></div><div className="mt-6 flex gap-2 overflow-x-auto">{available.map(item=><Button key={item.key} variant={item.key===tab.key?"default":"outline"} onClick={()=>setActive(item.key)}><item.icon/>{item.label}</Button>)}</div>{tab.key==="invoices"&&<div className="relative mt-4 max-w-lg"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={event=>setSearch(event.target.value)} className="pr-10" placeholder="الفاتورة، اسم العضو، العضوية، الجوال أو الهوية..."/></div>}{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}<Card className="mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right"><thead className="bg-secondary/50"><tr>{tab.fields.map(field=><th key={field[0]} className="px-5 py-4 text-xs text-muted-foreground">{field[1]}</th>)}<th className="px-5 py-4 text-xs text-muted-foreground">الإجراء</th></tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={String(row.id??index)}>{tab.fields.map(field=><td key={field[0]} className="px-5 py-4 text-sm">{renderCell(tab.key,row,field[0])}</td>)}<td className="px-5 py-3"><FinanceActions tab={tab.key} row={row} busy={busy===String(row.id)} canManage={tab.key==="income"?context.canAccess(["finance.other-income.manage"]):tab.key==="commissions"?context.canAccess(["coaching.commissions.manage"]):tab.key==="payments"?context.canAccess(["finance.refunds.issue"]):tab.key==="expenses"?context.canAccess(["finance.expenses.manage","finance.expenses.approve","finance.expenses.pay"]):false} onAction={value=>void transition(row,value)}/></td></tr>)}</tbody></table>{loading?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:!rows.length&&!error?<p className="p-12 text-center text-sm text-muted-foreground">لا توجد سجلات في الفترة الحالية.</p>:null}</div></Card>{dialog&&<ActionDialog operationId={dialog} organizationId={context.organizationId} branchId={context.branchId} onClose={()=>setDialog(undefined)} onSaved={()=>void load()}/>}</div>}

function FinanceActions({tab,row,busy,canManage,onAction}:{tab:string;row:Row;busy:boolean;canManage:boolean;onAction:(value:string)=>void}){if(tab==="invoices")return <Link href={`/finance/invoices/${String(row.id)}`} className={buttonVariants({size:"sm",variant:"outline"})}><Eye/>عرض التفاصيل</Link>;if(!canManage||tab==="refunds")return <span className="text-xs text-muted-foreground">عرض فقط</span>;const status=String(row.status??"");let actions:string[][]=[];if(tab==="income"&&status==="RECORDED")actions=[["VOIDED","إلغاء القيد"]];if(tab==="commissions"&&status==="ACCRUED")actions=[["APPROVED","اعتماد"],["VOIDED","إلغاء"]];if(tab==="commissions"&&status==="APPROVED")actions=[["PAID","تسجيل السداد"]];if(tab==="payments"&&status!=="REFUNDED"&&Number(row.amountMinor??0)>Number(row.refundedMinor??0))actions=[["REFUND","استرجاع"]];if(tab==="expenses"&&status==="RECORDED")actions=[["SUBMIT","إرسال للاعتماد"],["VOID","إلغاء"]];if(tab==="expenses"&&status==="SUBMITTED")actions=[["APPROVE","اعتماد"],["VOID","رفض وإلغاء"]];if(tab==="expenses"&&status==="APPROVED")actions=[["PAY","تسجيل السداد"],["VOID","إلغاء"]];return <div className="flex gap-2">{actions.map(([value,label])=><Button key={value} size="sm" variant={["VOIDED","VOID"].includes(value)?"destructive":"outline"} disabled={busy} onClick={()=>onAction(value)}>{busy?<Loader2 className="animate-spin"/>:label}</Button>)}{!actions.length&&<span className="text-xs text-muted-foreground">لا إجراء متاح</span>}</div>}
function renderCell(tab:string,row:Row,key:string){const value=row[key]??fallback(row,key);if(tab==="invoices"&&key==="invoiceNumber"&&row.id)return <Link href={`/finance/invoices/${String(row.id)}`} className="font-bold text-primary underline-offset-4 hover:underline">{display(value,key)}</Link>;return display(value,key)}
function list(value:unknown):Row[]{if(Array.isArray(value))return value as Row[];if(value&&typeof value==="object"&&Array.isArray((value as {items?:unknown[]}).items))return (value as {items:Row[]}).items;return[]}
function fallback(row:Row,key:string){const aliases:Record<string,string[]>={buyerName:["memberName"],categoryName:["category_name","categoryCode"],trainerName:["displayName"]};for(const candidate of aliases[key]??[]){if(row[candidate]!=null)return row[candidate]}return undefined}
function display(value:unknown,key:string){if(value==null||value==="")return"—";if(typeof value==="boolean")return value?"نعم":"لا";if(typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))return"بيانات مرتبطة";if(key.toLowerCase().includes("minor"))return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(Number(value)/100);if(typeof value==="string"&&key.endsWith("At")){const date=new Date(value);if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeZone:"Asia/Riyadh"}).format(date)}const labels:Record<string,string>={RECORDED:"مسجل",SUBMITTED:"بانتظار الاعتماد",VOIDED:"ملغى",ACCRUED:"مستحق",APPROVED:"معتمد",PAID:"مدفوع",REFUNDED:"مسترجع",CASH:"نقدي",CARD:"بطاقة",BANK_TRANSFER:"تحويل بنكي",GATEWAY:"بوابة دفع",WALLET:"محفظة",PERSONAL_TRAINING:"تدريب شخصي",SUBSCRIPTION_SALE:"بيع اشتراك",MANUAL_ADJUSTMENT:"تسوية يدوية"};return labels[String(value)]??String(value)}
function monthRange(){const to=new Date();to.setDate(to.getDate()+1);const from=new Date();from.setDate(from.getDate()-31);return{from:from.toISOString(),to:to.toISOString()}}
