"use client"

import { useEffect, useState } from "react"
import { Activity, CalendarDays, CreditCard, Dumbbell, Loader2, ReceiptText, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { apiRequest } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Member={organizationId:string;memberId:string;registrationBranchId:string;memberName:string;memberNumber:string;canManageMembership?:boolean;canBook?:boolean}
type Row=Record<string,unknown>
const tabs=[{key:"subscriptions",label:"اشتراكاتي",icon:CreditCard},{key:"reservations",label:"حجوزاتي",icon:CalendarDays},{key:"invoices",label:"فواتيري",icon:ReceiptText},{key:"attendance",label:"حضوري",icon:Activity},{key:"training-plans",label:"خطط التدريب",icon:Dumbbell}] as const
export function MemberSelfOverview({member}:{member:Member}){const[active,setActive]=useState<(typeof tabs)[number]["key"]>("subscriptions");const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[busy,setBusy]=useState("")
 async function load(){setLoading(true);setError("");try{const response=await apiRequest<unknown>(`/self/organizations/${member.organizationId}/members/${member.memberId}/${active}?limit=100`);setRows(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل بيانات العضوية."))}finally{setLoading(false)}}useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[active,member.memberId,member.organizationId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function subscriptionAction(row:Row,action:"freezes"|"resumptions"|"cancellations"){const id=String(row.id??row.subscriptionId??"");if(!id)return;setBusy(id);try{let body:Record<string,unknown>={expectedVersion:Number(row.version??1)};if(action==="freezes")body={...body,requestedDays:30,reason:"طلب العضو عبر الخدمة الذاتية"};if(action==="cancellations"){const reason=window.prompt("اكتب سبب طلب إلغاء الاشتراك");if(!reason||reason.trim().length<3)return;body={...body,reason}}await apiRequest(`/self/organizations/${member.organizationId}/members/${member.memberId}/subscriptions/${id}/${action}`,{method:"POST",body:JSON.stringify(body)});await load()}catch(reason){setError(humanError(reason,"تعذر تحديث الاشتراك."))}finally{setBusy("")}}
 async function cancelReservation(row:Row){const id=String(row.id??row.reservationId??"");const reason=window.prompt("سبب إلغاء الحجز");if(!id||!reason||reason.trim().length<3)return;setBusy(id);try{await apiRequest(`/self/organizations/${member.organizationId}/members/${member.memberId}/reservations/${id}/cancellations`,{method:"POST",body:JSON.stringify({expectedVersion:Number(row.version??1),reason})});await load()}catch(value){setError(humanError(value,"تعذر إلغاء الحجز."))}finally{setBusy("")}}
 return <Card className="mt-5"><CardContent className="p-5"><div className="flex flex-wrap items-center gap-3"><div><h2 className="font-black">{member.memberName}</h2><p className="mt-1 text-xs text-muted-foreground">رقم العضوية: {member.memberNumber}</p></div><Button className="mr-auto" variant="outline" size="sm" onClick={()=>void load()}><RefreshCw/>تحديث</Button></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{tabs.map(tab=><Button key={tab.key} variant={active===tab.key?"default":"outline"} size="sm" onClick={()=>setActive(tab.key)}><tab.icon/>{tab.label}</Button>)}</div>{error&&<p className="mt-3 rounded-xl bg-red-500/10 p-3 text-xs text-red-600">{error}</p>}{loading?<div className="grid min-h-40 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:<div className="mt-4 space-y-3">{rows.map((row,index)=><div key={String(row.id??index)} className="rounded-xl border p-4"><div className="flex flex-wrap items-start gap-3"><div><p className="text-sm font-black">{title(row,active,index)}</p><p className="mt-2 text-xs text-muted-foreground">{summary(row,active)}</p></div><div className="mr-auto flex gap-2">{active==="subscriptions"&&member.canManageMembership&&<SubscriptionButtons row={row} busy={busy===String(row.id)} onAction={value=>void subscriptionAction(row,value)}/>} {active==="reservations"&&member.canBook&&!["CANCELLED","COMPLETED","NO_SHOW"].includes(String(row.status))&&<Button size="sm" variant="destructive" disabled={busy===String(row.id)} onClick={()=>void cancelReservation(row)}>إلغاء الحجز</Button>}</div></div></div>)}{!rows.length&&<p className="py-10 text-center text-sm text-muted-foreground">لا توجد سجلات في هذا القسم.</p>}</div>}</CardContent></Card>}
function SubscriptionButtons({row,busy,onAction}:{row:Row;busy:boolean;onAction:(value:"freezes"|"resumptions"|"cancellations")=>void}){const status=String(row.status??"");return <>{["ACTIVE","ACTIVE_PROVISIONAL"].includes(status)&&<><Button size="sm" variant="outline" disabled={busy} onClick={()=>onAction("freezes")}>تجميد 30 يومًا</Button><Button size="sm" variant="destructive" disabled={busy} onClick={()=>onAction("cancellations")}>طلب إلغاء</Button></>}{status==="FROZEN"&&<Button size="sm" disabled={busy} onClick={()=>onAction("resumptions")}>استئناف</Button>}</>}
function list(value:unknown):Row[]{if(Array.isArray(value))return value as Row[];if(value&&typeof value==="object"&&Array.isArray((value as {items?:unknown[]}).items))return (value as {items:Row[]}).items;return[]}
function title(row:Row,active:string,index:number){return String(row.packageName??row.resourceName??row.invoiceNumber??row.name??row.planName??({subscriptions:"اشتراك",reservations:"حجز",invoices:"فاتورة",attendance:"زيارة",["training-plans"]:"خطة تدريب"} as Record<string,string>)[active]??`سجل ${index+1}`)}
function summary(row:Row,active:string){if(active==="invoices")return `الإجمالي ${money(row.grossMinor)} · المدفوع ${money(row.paidMinor)} · ${status(row.status)}`;const date=row.startsAt??row.attemptedAt??row.issuedAt??row.createdAt??row.termStart;return `${date?formatDate(date):""}${date?" · ":""}${status(row.status??row.decision??"")}`}
function money(value:unknown){return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format((Number(value)||0)/100)}
function formatDate(value:unknown){const date=new Date(String(value));return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(date)}
function status(value:unknown){return({ACTIVE:"نشط",ACTIVE_PROVISIONAL:"نشط مؤقتًا",FROZEN:"مجمّد",EXPIRED:"منتهي",CANCELLED:"ملغى",CONFIRMED:"مؤكد",COMPLETED:"مكتمل",NO_SHOW:"لم يحضر",ISSUED:"صادرة",PARTIALLY_PAID:"مدفوعة جزئيًا",PAID:"مدفوعة",ACCEPTED:"دخول مسموح",REJECTED:"دخول مرفوض"} as Record<string,string>)[String(value)]??String(value)}
