"use client"

import { useEffect, useState } from "react"
import { CalendarPlus, CreditCard, Loader2, RefreshCw, ShoppingBag } from "lucide-react"
import { apiRequest, createIdempotencyKey } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { useToast } from "@/components/toast-provider"

type Row=Record<string,unknown>
type Member={organizationId:string;memberId:string;registrationBranchId:string;canBook?:boolean;canManageMembership?:boolean}
type Tab="packages"|"services"|"booking"
type Quote={targetName:string;baseAmountMinor:string;discountMinor:string;netMinor:string;taxMinor:string;grossMinor:string;taxInclusive:boolean;promotion?:{name:string}}

export function MemberMarketplace({member}:{member:Member}){
 const toast=useToast()
 const[tab,setTab]=useState<Tab>(member.canManageMembership?"packages":"booking"),[items,setItems]=useState<Row[]>([]),[slots,setSlots]=useState<Row[]>([]),[resource,setResource]=useState<Row>(),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("")
 const allowed=(tab==="booking"&&member.canBook)||(tab!=="booking"&&member.canManageMembership)
 async function load(){if(!allowed)return;setLoading(true);setError("");setSlots([]);setResource(undefined);try{const suffix=tab==="packages"?"packages":tab==="services"?"services":"bookable-resources";const response=await apiRequest<unknown>(`/self/organizations/${member.organizationId}/${suffix}?branchId=${member.registrationBranchId}`);setItems(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل الخيارات المتاحة."));setItems([])}finally{setLoading(false)}}
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[tab,member.memberId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function buy(item:Row,type:"PACKAGE"|"SERVICE"){const id=String(item.id??"");if(!id)return;setBusy(id);setError("");try{const quote=(await apiRequest<Quote>(`/self/organizations/${member.organizationId}/quotes`,{method:"POST",body:JSON.stringify({branchId:member.registrationBranchId,targetType:type,targetId:id,quantity:1,memberSegment:"OTHER"})})).data;if(!window.confirm(summary(quote)))return;const order=await checkout({type:type==="PACKAGE"?"MEMBERSHIP":"SERVICE",targetId:id,quantity:1,accessBranchId:type==="PACKAGE"?member.registrationBranchId:undefined});toast.success(invoiceSuccess(order,"تم تسجيل طلبك بنجاح. برجاء السداد في استقبال النادي لإتمام الطلب."))}catch(reason){setError(humanError(reason,"تعذر إنشاء الطلب."))}finally{setBusy("")}}
 async function chooseResource(item:Row){const id=String(item.id??"");if(!id)return;setResource(item);setBusy(id);setError("");try{const from=new Date(),to=new Date();to.setDate(to.getDate()+30);const response=await apiRequest<unknown>(`/self/organizations/${member.organizationId}/bookable-resources/${id}/session-slots?branchId=${member.registrationBranchId}&from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`);setSlots(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل المواعيد المتاحة."));setSlots([])}finally{setBusy("")}}
 async function book(slot:Row){if(!resource)return;const id=String(slot.id??""),serviceId=String(resource.serviceId??"");if(!id||!serviceId)return;setBusy(id);setError("");try{const order=await checkout({type:"BOOKING",targetId:serviceId,quantity:1,booking:{resourceId:String(resource.id),type:bookingType(resource.resourceType),sessionSlotId:id,seats:1}});toast.success(invoiceSuccess(order,"تم تسجيل الحجز بنجاح. برجاء السداد في استقبال النادي لإتمامه."));await chooseResource(resource)}catch(reason){setError(humanError(reason,"تعذر تأكيد الحجز."))}finally{setBusy("")}}
 async function checkout(line:Record<string,unknown>){return (await apiRequest<Row>(`/self/organizations/${member.organizationId}/members/${member.memberId}/orders`,{method:"POST",idempotencyKey:createIdempotencyKey(),body:JSON.stringify({sellingBranchId:member.registrationBranchId,memberSegment:"OTHER",lines:[line]})})).data}
 const tabs:Array<[Tab,string]>=[...(member.canManageMembership?[["packages","الباقات"],["services","الخدمات"]] as Array<[Tab,string]>:[]),...(member.canBook?[["booking","حجز موعد"]] as Array<[Tab,string]>:[])]
 if(!tabs.length)return null
 return <Card className="mt-5"><CardContent className="p-5"><div className="flex flex-wrap items-start gap-3"><div><div className="flex items-center gap-2"><ShoppingBag className="size-5 text-primary"/><h2 className="font-black">الشراء والحجز</h2></div><p className="mt-1 text-xs leading-5 text-muted-foreground">الخيارات المنشورة والمتاحة فعليًا في فرع العضو.</p></div><Button className="mr-auto" variant="outline" size="icon" onClick={()=>void load()} aria-label="تحديث"><RefreshCw/></Button></div><div className="mt-4 flex gap-2">{tabs.map(([key,label])=><Button key={key} size="sm" variant={tab===key?"default":"outline"} onClick={()=>setTab(key)}>{key==="booking"?<CalendarPlus/>:<CreditCard/>}{label}</Button>)}</div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-xs text-red-600">{error}</p>}{loading?<div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map((item,index)=><div key={String(item.id??index)} className={`rounded-xl border p-4 ${resource?.id===item.id?"border-primary":""}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{String(item.name??item.code??"خيار متاح")}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{String(item.description??item.facilityName??item.categoryName??"")}</p></div>{item.amountMinor!=null&&<Badge variant="outline">{money(item.amountMinor)}</Badge>}</div><Button className="mt-4 w-full" size="sm" disabled={Boolean(busy)} onClick={()=>tab==="booking"?void chooseResource(item):void buy(item,tab==="packages"?"PACKAGE":"SERVICE")}>{busy===String(item.id)?<Loader2 className="animate-spin"/>:tab==="booking"?<CalendarPlus/>:<ShoppingBag/>}{tab==="booking"?"عرض المواعيد":"عرض السعر والمتابعة"}</Button></div>)}{!items.length&&<p className="py-8 text-center text-xs text-muted-foreground lg:col-span-2">لا توجد خيارات منشورة لهذا الفرع حاليًا.</p>}</div>}{resource&&<div className="mt-5 border-t pt-5"><h3 className="text-sm font-black">المواعيد المتاحة — {String(resource.name??"")}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{slots.map((slot,index)=><Button key={String(slot.id??index)} variant="outline" className="h-auto justify-between py-3" disabled={Boolean(busy)} onClick={()=>void book(slot)}><span>{date(slot.startsAt)}</span><span className="text-[10px] text-muted-foreground">متاح {String(slot.availableCount??"")}</span>{busy===String(slot.id)&&<Loader2 className="animate-spin"/>}</Button>)}{!slots.length&&<p className="text-xs text-muted-foreground">لا توجد مواعيد شاغرة خلال الثلاثين يومًا القادمة.</p>}</div></div>}</CardContent></Card>
}

function list(value:unknown):Row[]{return Array.isArray(value)?value as Row[]:value&&typeof value==="object"&&Array.isArray((value as{items?:Row[]}).items)?(value as{items:Row[]}).items:[]}
function money(value:unknown){return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(Number(value)/100)}
function date(value:unknown){const parsed=new Date(String(value));return Number.isNaN(parsed.getTime())?"موعد":new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(parsed)}
function bookingType(value:unknown):"COURT"|"CLASS"|"PERSONAL_TRAINING"{const type=String(value);return type==="CLASS"||type==="PERSONAL_TRAINING"?type:"COURT"}
function invoiceSuccess(order:Row,message:string){const invoiceNumber=String(order.invoiceNumber??"");return invoiceNumber?`${message} رقم الفاتورة: ${invoiceNumber}.`:message}
function summary(quote:Quote){return `${quote.targetName}\n\nقبل الخصم: ${money(quote.baseAmountMinor)}\nالخصم: ${money(quote.discountMinor)}${quote.promotion?` (${quote.promotion.name})`:""}\nالصافي قبل الضريبة: ${money(quote.netMinor)}\nالضريبة: ${money(quote.taxMinor)}\nالإجمالي المطلوب: ${money(quote.grossMinor)}\n\nمتابعة إنشاء الطلب والفاتورة؟`}
