"use client"

import { useEffect, useMemo, useState } from "react"
import { AlertCircle, CalendarClock, ClipboardCheck, Loader2, LockKeyhole, Plus, RefreshCw, UsersRound } from "lucide-react"
import { ActionDialog } from "@/components/action-dialog"
import { useAppContext } from "@/components/app-context"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { apiRequest } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Row=Record<string,unknown>
type Tab={key:string;label:string;icon:typeof CalendarClock;permission:string;path:(org:string,branch:string,range:{from:string;to:string})=>string;fields:Array<{key:string;label:string}>}

const tabs:Tab[]=[
 {key:"shifts",label:"المناوبات",icon:CalendarClock,permission:"workforce.shifts.read",path:(o,b,r)=>`/organizations/${o}/employee-shifts?branchId=${b}&from=${encodeURIComponent(r.from)}&to=${encodeURIComponent(r.to)}`,fields:[{key:"employeeName",label:"الموظف"},{key:"startsAt",label:"البداية"},{key:"endsAt",label:"النهاية"},{key:"status",label:"الحالة"}]},
 {key:"attendance",label:"حضور الموظفين",icon:UsersRound,permission:"workforce.shifts.read",path:(o,b,r)=>`/organizations/${o}/employee-attendance?branchId=${b}&from=${encodeURIComponent(r.from)}&to=${encodeURIComponent(r.to)}`,fields:[{key:"employeeName",label:"الموظف"},{key:"eventType",label:"الحركة"},{key:"occurredAt",label:"الوقت"},{key:"accessMethod",label:"الطريقة"}]},
 {key:"requests",label:"الطلبات الإلكترونية",icon:ClipboardCheck,permission:"online-requests.read",path:(o,b)=>`/organizations/${o}/online-requests?branchId=${b}&limit=100`,fields:[{key:"requesterName",label:"صاحب الطلب"},{key:"requestType",label:"النوع"},{key:"requesterPhoneE164",label:"الجوال"},{key:"status",label:"الحالة"}]},
 {key:"feedback",label:"الشكاوى والمقترحات",icon:AlertCircle,permission:"feedback.read",path:(o,b)=>`/organizations/${o}/feedback-cases?branchId=${b}&limit=100`,fields:[{key:"subject",label:"الموضوع"},{key:"caseType",label:"النوع"},{key:"priority",label:"الأولوية"},{key:"status",label:"الحالة"}]},
 {key:"lockers",label:"الخزائن",icon:LockKeyhole,permission:"lockers.read",path:(o,b)=>`/organizations/${o}/lockers?branchId=${b}&limit=200`,fields:[{key:"code",label:"رقم الخزانة"},{key:"lockerType",label:"النوع"},{key:"status",label:"الحالة"},{key:"memberName",label:"المستخدم الحالي"}]},
]

export function OperationsWorkspace(){
 const context=useAppContext();const available=tabs.filter(tab=>context.canAccess([tab.permission]));const[active,setActive]=useState(available[0]?.key??"");const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[action,setAction]=useState(false);const[busy,setBusy]=useState("")
 const range=useMemo(()=>monthRange(),[]);const tab=available.find(item=>item.key===active)??available[0]
 async function load(){if(!tab||!context.organizationId||!context.branchId)return;setLoading(true);setError("");try{const response=await apiRequest<unknown>(tab.path(context.organizationId,context.branchId,range));setRows(list(response.data))}catch(reason){setError(humanError(reason,"تعذر تحميل بيانات مركز العمليات."))}finally{setLoading(false)}}
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[active,context.branchId,context.organizationId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function transition(row:Row,status:string){const id=String(row.id??"");if(!id||!tab)return;setBusy(id);setError("");try{let path="",body:Record<string,unknown>={branchId:context.branchId,status,expectedVersion:Number(row.version??1)};if(tab.key==="shifts")path=`/organizations/${context.organizationId}/employee-shifts/${id}/transitions`;if(tab.key==="requests")path=`/organizations/${context.organizationId}/online-requests/${id}/transitions`;if(tab.key==="lockers")path=`/organizations/${context.organizationId}/lockers/${id}/transitions`;if(tab.key==="feedback"){path=`/organizations/${context.organizationId}/feedback-cases/${id}/transitions`;if(status==="RESOLVED"){const resolution=window.prompt("اكتب نتيجة معالجة الشكوى أو المقترح");if(!resolution||resolution.trim().length<3)return;body={...body,resolution}}}await apiRequest(path,{method:"POST",body:JSON.stringify(body)});await load()}catch(reason){setError(humanError(reason,"تعذر تنفيذ الإجراء."))}finally{setBusy("")}}
 if(!tab)return <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">لا توجد مهام تشغيلية مخصصة لهذا الحساب.</CardContent></Card>
 return <div className="fade-up"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">تشغيل الفرع</Badge><h1 className="mt-3 text-3xl font-black">مركز العمليات</h1><p className="mt-2 text-sm text-muted-foreground">المناوبات والحضور والطلبات والشكاوى والخزائن الخاصة بالفرع الحالي.</p></div><div className="mr-auto flex gap-2">{active==="shifts"&&context.canAccess(["workforce.shifts.manage"])&&<Button onClick={()=>setAction(true)}><Plus/>جدولة مناوبة</Button>}<Button variant="outline" onClick={()=>void load()}><RefreshCw/>تحديث</Button></div></div>
  <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{available.map(item=><Button key={item.key} variant={item.key===tab.key?"default":"outline"} onClick={()=>setActive(item.key)}><item.icon/>{item.label}</Button>)}</div>
  {error&&<p className="mt-4 rounded-xl bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}
  <Card className="mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right"><thead className="bg-secondary/50"><tr>{tab.fields.map(field=><th key={field.key} className="px-5 py-4 text-xs text-muted-foreground">{field.label}</th>)}<th className="px-5 py-4 text-xs text-muted-foreground">الإجراء</th></tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={String(row.id??index)}>{tab.fields.map(field=><td key={field.key} className="px-5 py-4 text-sm">{display(row[field.key]??alias(row,field.key),field.key)}</td>)}<td className="px-5 py-3"><Actions tab={tab.key} row={row} busy={busy===String(row.id)} canManage={context.canAccess([managePermission(tab.key)])} onAction={status=>void transition(row,status)}/></td></tr>)}</tbody></table>{loading?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:!rows.length&&!error?<p className="p-12 text-center text-sm text-muted-foreground">لا توجد سجلات في الفترة الحالية.</p>:null}</div></Card>
  {action&&<ActionDialog operationId="scheduleEmployeeShift" organizationId={context.organizationId} branchId={context.branchId} onClose={()=>setAction(false)} onSaved={()=>void load()}/>}</div>
}

function Actions({tab,row,busy,canManage,onAction}:{tab:string;row:Row;busy:boolean;canManage:boolean;onAction:(status:string)=>void}){if(!canManage||tab==="attendance")return <span className="text-xs text-muted-foreground">عرض فقط</span>;const status=String(row.status??"");let actions:Array<[string,string]>=[];if(tab==="shifts")actions=status==="SCHEDULED"?[["IN_PROGRESS","بدء"],["CANCELLED","إلغاء"]]:status==="IN_PROGRESS"?[["COMPLETED","إنهاء"]]:[];if(tab==="requests"&&status==="PENDING")actions=[["APPROVED","اعتماد"],["REJECTED","رفض"]];if(tab==="feedback")actions=status==="OPEN"?[["IN_REVIEW","بدء المعالجة"]]:status==="IN_REVIEW"?[["RESOLVED","حل وإغلاق"]]:[];if(tab==="lockers")actions=status==="AVAILABLE"?[["MAINTENANCE","صيانة"]]:status==="MAINTENANCE"?[["AVAILABLE","إتاحة"]]:[];return <div className="flex gap-2">{actions.map(([value,label])=><Button key={value} size="sm" variant={value==="REJECTED"||value==="CANCELLED"?"destructive":"outline"} disabled={busy} onClick={()=>onAction(value)}>{busy?<Loader2 className="animate-spin"/>:label}</Button>)}{!actions.length&&<span className="text-xs text-muted-foreground">لا إجراء متاح</span>}</div>}
function managePermission(tab:string){return({shifts:"workforce.shifts.manage",requests:"online-requests.manage",feedback:"feedback.manage",lockers:"lockers.manage"} as Record<string,string>)[tab]??""}
function list(value:unknown):Row[]{if(Array.isArray(value))return value as Row[];if(value&&typeof value==="object"&&Array.isArray((value as {items?:unknown[]}).items))return (value as {items:Row[]}).items;return[]}
function alias(row:Row,key:string){const aliases:Record<string,string[]>={employeeName:["name","fullName","employeeNumber"],memberName:["assignedMemberName","memberNumber"],requesterPhoneE164:["phoneE164"],occurredAt:["createdAt"]};for(const candidate of aliases[key]??[]){if(row[candidate]!=null)return row[candidate]}return undefined}
function display(value:unknown,key:string){if(value===undefined||value===null||value==="")return "—";if(typeof value==="string"&&/(At|Date)$/.test(key)){const date=new Date(value);if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(date)}if(typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/iu.test(value))return "بيانات مرتبطة";const labels:Record<string,string>={SCHEDULED:"مجدولة",IN_PROGRESS:"جارية",COMPLETED:"مكتملة",CANCELLED:"ملغاة",PENDING:"قيد المراجعة",APPROVED:"معتمد",REJECTED:"مرفوض",OPEN:"مفتوحة",IN_REVIEW:"قيد المعالجة",RESOLVED:"تم الحل",CLOSED:"مغلقة",AVAILABLE:"متاحة",MAINTENANCE:"صيانة",INACTIVE:"غير نشطة",CLOCK_IN:"دخول",CLOCK_OUT:"انصراف",MANUAL:"يدوي",COMPLAINT:"شكوى",SUGGESTION:"مقترح",URGENT:"عاجلة",HIGH:"مرتفعة",NORMAL:"عادية",LOW:"منخفضة"};return labels[String(value)]??String(value)}
function monthRange(){const to=new Date();to.setDate(to.getDate()+7);const from=new Date();from.setDate(from.getDate()-30);return{from:from.toISOString(),to:to.toISOString()}}
