"use client"

import { useEffect, useMemo, useState } from "react"
import { BarChart3, ChevronLeft, ChevronRight, Download, Eye, MoreHorizontal, Plus, Search, SlidersHorizontal, Sparkles, X } from "lucide-react"
import type { SectionConfig } from "@/lib/sections"
import { StatusBadge } from "@/components/status-badge"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useAppContext } from "@/components/app-context"
import { endpoints } from "@/lib/endpoint-catalog"
import { apiRequest, hasRuntimeApi } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"
import { ActionDialog } from "@/components/action-dialog"

export function ResourcePage({ config }: { config:SectionConfig }) {
 const context=useAppContext()
 const [query,setQuery]=useState("")
 const [status,setStatus]=useState("")
 const [showAction,setShowAction]=useState(false)
 const [selectedRow,setSelectedRow]=useState<string[]>()
 const [serverRows,setServerRows]=useState<string[][]>(config.rows)
 const [loading,setLoading]=useState(hasRuntimeApi())
 const [error,setError]=useState("")
 const [nextCursor,setNextCursor]=useState<string>()
 const statuses=useMemo(()=>config.statusIndex===undefined?[]:[...new Set(serverRows.map(row=>row[config.statusIndex!]).filter(Boolean))],[config.statusIndex,serverRows])
 const rows=useMemo(()=>serverRows.filter(row=>row.some(c=>c.toLowerCase().includes(query.toLowerCase()))&&(!status||config.statusIndex===undefined||row[config.statusIndex]===status)),[config.statusIndex,serverRows,query,status])
 const listOperation=endpoints.find(item=>item.operationId===config.listOperationId)
 useEffect(()=>{const frame=requestAnimationFrame(()=>{if(!hasRuntimeApi()||!listOperation||!context.organizationId){setLoading(false);return}let path=listOperation.path.replace("{organizationId}",context.organizationId).replace("{branchId}",context.branchId);const separator=path.includes("?")?"&":"?";if(context.branchId&&!path.includes("{branchId}"))path+=`${separator}branchId=${encodeURIComponent(context.branchId)}`;apiRequest<unknown>(path.replace(/^\/api\/v1/,""),{fullPath:false}).then(response=>{const payload=response.data as unknown;const list=Array.isArray(payload)?payload:(payload&&typeof payload==="object"&&"items" in payload?(payload as {items:unknown[]}).items:[]);setServerRows(list.map(item=>config.fields.map(field=>displayValue(item,field))));setNextCursor(response.meta?.nextCursor)}).catch(err=>setError(humanError(err,"تعذر تحميل البيانات. حاول مرة أخرى."))).finally(()=>setLoading(false))});return()=>cancelAnimationFrame(frame)},[config.fields,context.branchId,context.organizationId,listOperation])
 function exportCsv(){const escape=(value:string)=>`"${value.replaceAll('"','""')}"`;const csv=[config.columns,...rows].map(row=>row.map(escape).join(",")).join("\n");const url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`go-${config.listOperationId}.csv`;link.click();URL.revokeObjectURL(url)}
 async function loadMore(){if(!nextCursor||!listOperation)return;setLoading(true);try{const path=listOperation.path.replace("{organizationId}",context.organizationId).replace("{branchId}",context.branchId);const params=new URLSearchParams({cursor:nextCursor});if(context.branchId&&!listOperation.path.includes("{branchId}"))params.set("branchId",context.branchId);const response=await apiRequest<unknown>(`${path.replace(/^\/api\/v1/,"")}?${params}`);const payload=response.data;const list=Array.isArray(payload)?payload:(payload&&typeof payload==="object"&&"items" in payload?(payload as {items:unknown[]}).items:[]);setServerRows(current=>[...current,...list.map(item=>config.fields.map(field=>displayValue(item,field)))]);setNextCursor(response.meta?.nextCursor)}catch(err){setError(humanError(err,"تعذر تحميل المزيد. حاول مرة أخرى."))}finally{setLoading(false)}}
 return <div className="fade-up">
   <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline" className="mb-3 border-primary/30 bg-primary/8 text-amber-700 dark:text-primary">{config.eyebrow}</Badge><h1 className="text-2xl font-black tracking-tight sm:text-3xl">{config.title}</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-muted-foreground">{config.description}</p></div><div className="flex gap-2"><Button size="lg" variant="outline" onClick={exportCsv} disabled={!rows.length}><Download/>تصدير</Button>{config.createOperationId&&<Button size="lg" className="brand-shadow" onClick={()=>setShowAction(true)}><Plus/>{config.action}</Button>}</div></div>
   <section className="grid gap-4 md:grid-cols-3">{config.metrics.map((m,i)=><Card key={m.label}><CardContent className="flex items-center gap-4 p-5"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${i===0?"bg-primary/15 text-amber-600":i===1?"bg-blue-500/10 text-blue-600":"bg-emerald-500/10 text-emerald-600"}`}>{i===0?<BarChart3/>:i===1?<Sparkles/>:<SlidersHorizontal/>}</span><div><p className="text-[11px] font-semibold text-muted-foreground">{m.label}</p><p className="mt-1 text-xl font-black">{m.value}</p><p className="mt-1 text-[9px] text-muted-foreground">{m.note}</p></div></CardContent></Card>)}</section>
   <Card className="mt-5 overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center"><div className="relative w-full sm:max-w-md"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pr-10" placeholder={config.search}/></div>{statuses.length>0&&<select aria-label="تصفية حسب الحالة" value={status} onChange={event=>setStatus(event.target.value)} className="h-10 rounded-xl border bg-background px-3 text-xs outline-none focus:border-primary"><option value="">كل الحالات</option>{statuses.map(item=><option key={item} value={item}>{statusLabel(item)}</option>)}</select>}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-right"><thead><tr className="bg-secondary/45">{config.columns.map(h=><th key={h} className="whitespace-nowrap px-5 py-3 text-[10px] font-bold text-muted-foreground">{h}</th>)}<th className="w-10 px-4"><span className="sr-only">عرض التفاصيل</span></th></tr></thead><tbody className="divide-y">{rows.map((row,r)=><tr key={r} className="group transition hover:bg-secondary/30">{row.map((cell,c)=><td key={c} className="whitespace-nowrap px-5 py-4 text-xs first:font-bold">{c===config.statusIndex?<StatusBadge status={cell}/>:cell}</td>)}<td className="px-4"><Button variant="ghost" size="icon-sm" aria-label="عرض التفاصيل" onClick={()=>setSelectedRow(row)}><MoreHorizontal/></Button></td></tr>)}</tbody></table>{loading?<div className="grid place-items-center px-6 py-16"><span className="size-9 animate-spin rounded-full border-4 border-primary border-t-transparent"/></div>:error?<div className="grid place-items-center px-6 py-16 text-center"><p className="text-sm font-bold text-red-600">تعذر عرض البيانات</p><p className="mt-1 text-xs text-muted-foreground">{error}</p></div>:rows.length===0&&<div className="grid place-items-center px-6 py-16 text-center"><span className="grid size-12 place-items-center rounded-2xl bg-secondary"><Search className="text-muted-foreground"/></span><p className="mt-4 text-sm font-bold">لا توجد نتائج</p><p className="mt-1 text-xs text-muted-foreground">جرّب تغيير البحث أو إزالة تصفية الحالة.</p></div>}</div>
    <div className="flex items-center justify-between border-t p-4"><p className="text-[10px] text-muted-foreground">عرض {rows.length} سجلًا · آخر تحديث الآن</p><div className="flex items-center gap-2"><Button variant="outline" size="icon-sm" disabled aria-label="السابق"><ChevronRight/></Button><span className="grid size-7 place-items-center rounded-lg bg-primary text-xs font-bold text-black">1</span><Button variant="outline" size="icon-sm" disabled={!nextCursor||loading} aria-label="تحميل المزيد" onClick={loadMore}><ChevronLeft/></Button></div></div>
   </Card>
   {showAction&&config.createOperationId&&<ActionDialog operationId={config.createOperationId} organizationId={context.organizationId} branchId={context.branchId} onClose={()=>setShowAction(false)}/>} 
   {selectedRow&&<div className="fixed inset-0 z-[75] grid place-items-end bg-black/60 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedRow(undefined)}}><section role="dialog" aria-modal="true" aria-labelledby="record-title" className="max-h-[90vh] w-full overflow-y-auto rounded-t-[28px] border bg-card p-5 shadow-2xl sm:max-w-xl sm:rounded-[28px] sm:p-6"><div className="flex items-center"><span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-amber-600"><Eye/></span><div className="mr-3"><p className="text-[10px] text-muted-foreground">ملخص السجل</p><h2 id="record-title" className="font-black">{selectedRow[0]}</h2></div><Button className="mr-auto" variant="ghost" size="icon" onClick={()=>setSelectedRow(undefined)} aria-label="إغلاق"><X/></Button></div><dl className="mt-6 grid gap-3 sm:grid-cols-2">{config.columns.map((label,index)=><div key={label} className="rounded-xl bg-secondary/55 p-4"><dt className="text-[10px] font-bold text-muted-foreground">{label}</dt><dd className="mt-2 text-sm font-bold">{index===config.statusIndex?<StatusBadge status={selectedRow[index]}/>:selectedRow[index]}</dd></div>)}</dl><Button className="mt-6 w-full" size="lg" onClick={()=>setSelectedRow(undefined)}>إغلاق</Button></section></div>}
 </div>
}

function displayValue(item:unknown,field:string){if(!item||typeof item!=="object")return "—";const record=item as Record<string,unknown>;const value=field.split(".").reduce<unknown>((current,key)=>current&&typeof current==="object"?(current as Record<string,unknown>)[key]:undefined,record);if(value===null||value===undefined||value==="")return "—";if(field.endsWith("Minor")&&(typeof value==="string"||typeof value==="number")){const amount=Number(value)/100;return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(amount)}if(/At$|On$/.test(field)&&typeof value==="string"){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:field.endsWith("At")?"short":undefined,timeZone:"Asia/Riyadh"}).format(date)}if(Array.isArray(value))return `${value.length} عناصر`;if(typeof value==="object")return "بيانات إضافية";return statusLabel(String(value))}

function statusLabel(value:string){return ({ACTIVE:"نشط",INACTIVE:"غير نشط",PENDING:"قيد المراجعة",FROZEN:"مجمّد",EXPIRED:"منتهي",CANCELLED:"ملغي",ACCEPTED:"مسموح",REJECTED:"مرفوض",PAID:"مدفوع",PARTIALLY_PAID:"مدفوع جزئيًا",DRAFT:"مسودة",SCHEDULED:"مجدول",COMPLETED:"مكتمل",NEW:"جديد",CONTACTED:"تم التواصل",QUALIFIED:"مؤهل",PREPARING:"قيد التحضير",READY:"جاهز"} as Record<string,string>)[value]??value}
