"use client"

import { useEffect, useMemo, useState } from "react"
import { CalendarDays, Dumbbell, HandCoins, Loader2, RefreshCw, Ruler, Users } from "lucide-react"
import { ActionDialog } from "@/components/action-dialog"
import { useAppContext } from "@/components/app-context"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { apiRequest } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"

type Row=Record<string,unknown>
const tabs=[{key:"members",label:"متدربوّي",icon:Users},{key:"schedule",label:"جدولي",icon:CalendarDays},{key:"plans",label:"خطط التدريب",icon:Dumbbell},{key:"commissions",label:"عمولاتي",icon:HandCoins}] as const
export function TrainerWorkspace(){const context=useAppContext();const[active,setActive]=useState<(typeof tabs)[number]["key"]>("members");const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[measurement,setMeasurement]=useState(false);const[busy,setBusy]=useState("");const range=useMemo(()=>monthRange(),[])
 async function load(){if(!context.organizationId)return;setLoading(true);setError("");try{const base=`/self/organizations/${context.organizationId}/trainer`;const path=active==="members"?`${base}/members`:active==="schedule"?`${base}/schedule?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`:active==="plans"?`${base}/training-plans?limit=100`:`${base}/commissions?limit=100`;const response=await apiRequest<unknown>(path);setRows(list(response.data))}catch(reason){setRows([]);setError(humanError(reason,"تعذر تحميل مساحة المدرب. تأكد من ربط حساب الموظف بملف مدرب نشط."))}finally{setLoading(false)}}
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[active,context.organizationId]) // eslint-disable-line react-hooks/exhaustive-deps
 async function complete(plan:Row,item:Row,status:"COMPLETED"|"SKIPPED"){const planId=String(plan.id??plan.planId??""),itemId=String(item.id??item.itemId??"");if(!planId||!itemId)return;setBusy(itemId);try{await apiRequest(`/self/organizations/${context.organizationId}/trainer/training-plans/${planId}/items/${itemId}/transitions`,{method:"POST",body:JSON.stringify({status})});await load()}catch(reason){setError(humanError(reason,"تعذر تحديث التمرين."))}finally{setBusy("")}}
 return <div className="fade-up"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">مساحة المدرب</Badge><h1 className="mt-3 text-3xl font-black">التدريب والمتابعة</h1><p className="mt-2 text-sm text-muted-foreground">تظهر هنا فقط الأعضاء والجلسات والخطط المرتبطة بك في فرعك.</p></div><div className="mr-auto flex gap-2">{context.canAccess(["measurements.manage"])&&<Button onClick={()=>setMeasurement(true)}><Ruler/>تسجيل قياس</Button>}<Button variant="outline" onClick={()=>void load()}><RefreshCw/>تحديث</Button></div></div><div className="mt-6 flex gap-2 overflow-x-auto">{tabs.map(tab=><Button key={tab.key} variant={tab.key===active?"default":"outline"} onClick={()=>setActive(tab.key)}><tab.icon/>{tab.label}</Button>)}</div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-4 text-sm text-red-600">{error}</p>}{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-primary"/></div>:active==="plans"?<Plans rows={rows} busy={busy} onComplete={complete}/>:<Cards active={active} rows={rows}/>} {measurement&&<ActionDialog operationId="recordSelfTrainerMeasurement" organizationId={context.organizationId} branchId={context.branchId} onClose={()=>setMeasurement(false)} onSaved={()=>void load()}/>}</div>}
function Cards({active,rows}:{active:string;rows:Row[]}){return <section className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((row,index)=><Card key={String(row.id??row.memberId??index)}><CardContent className="p-5"><p className="font-black">{text(row.memberName??row.name??row.title??row.serviceName??`سجل ${index+1}`)}</p><dl className="mt-4 space-y-2 text-xs">{Object.entries(row).filter(([key,value])=>value!=null&&!key.toLowerCase().includes("id")&&typeof value!=="object").slice(0,6).map(([key,value])=><div key={key} className="flex justify-between gap-4"><dt className="text-muted-foreground">{label(key)}</dt><dd className="font-semibold">{format(value,key)}</dd></div>)}</dl></CardContent></Card>)}{!rows.length&&<Card className="md:col-span-2"><CardContent className="p-12 text-center text-sm text-muted-foreground">لا توجد بيانات في {tabs.find(tab=>tab.key===active)?.label} حاليًا.</CardContent></Card>}</section>}
function Plans({rows,busy,onComplete}:{rows:Row[];busy:string;onComplete:(plan:Row,item:Row,status:"COMPLETED"|"SKIPPED")=>void}){return <section className="mt-4 space-y-4">{rows.map((plan,index)=><Card key={String(plan.id??index)}><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">{text(plan.name??`خطة تدريب ${index+1}`)}</h2><p className="mt-1 text-xs text-muted-foreground">{format(plan.status??"ACTIVE","status")}</p></div><Badge>{Array.isArray(plan.items)?plan.items.length:0} تمارين</Badge></div><div className="mt-4 space-y-2">{(Array.isArray(plan.items)?plan.items:[]).map((value,itemIndex)=>{const item=value as Row;const state=String(item.completionStatus??item.status??"PENDING");return <div key={String(item.id??itemIndex)} className="flex flex-wrap items-center gap-3 rounded-xl bg-secondary/50 p-3"><div><p className="text-sm font-bold">{text(item.exerciseName??item.name??`تمرين ${itemIndex+1}`)}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.sets?`${item.sets} مجموعات`:""} {item.repetitions?`· ${item.repetitions} تكرار`:""}</p></div><div className="mr-auto flex gap-2">{state==="PENDING"?<><Button size="sm" disabled={busy===String(item.id)} onClick={()=>onComplete(plan,item,"COMPLETED")}>تم التنفيذ</Button><Button size="sm" variant="outline" disabled={busy===String(item.id)} onClick={()=>onComplete(plan,item,"SKIPPED")}>تخطي</Button></>:<Badge variant="outline">{format(state,"status")}</Badge>}</div></div>})}</div></CardContent></Card>)}{!rows.length&&<p className="py-16 text-center text-sm text-muted-foreground">لا توجد خطط تدريب مرتبطة بك حاليًا.</p>}</section>}
function list(value:unknown):Row[]{if(Array.isArray(value))return value as Row[];if(value&&typeof value==="object"&&Array.isArray((value as {items?:unknown[]}).items))return (value as {items:Row[]}).items;return[]}
function text(value:unknown){return value==null?"—":String(value)}
function label(key:string){return({memberNumber:"رقم العضوية",startsAt:"البداية",endsAt:"النهاية",scheduledAt:"الموعد",status:"الحالة",commissionAmountMinor:"العمولة",sourceType:"المصدر",validFrom:"من",validUntil:"إلى"} as Record<string,string>)[key]??key}
function format(value:unknown,key:string){if(key.toLowerCase().includes("minor"))return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(Number(value)/100);if(typeof value==="string"&&/(At|From|Until)$/.test(key)){const date=new Date(value);if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:key.endsWith("At")?"short":undefined,timeZone:"Asia/Riyadh"}).format(date)}return({ACTIVE:"نشطة",PENDING:"لم ينفذ",COMPLETED:"مكتمل",SKIPPED:"تم التخطي",ACCRUED:"مستحق",APPROVED:"معتمد",PAID:"مدفوع"} as Record<string,string>)[String(value)]??String(value)}
function monthRange(){const from=new Date();from.setDate(from.getDate()-7);const to=new Date();to.setDate(to.getDate()+31);return{from:from.toISOString(),to:to.toISOString()}}
