export type SectionConfig={title:string;eyebrow:string;description:string;action:string;search:string;listOperationId:string;createOperationId?:string;fields:string[];metrics:Array<{label:string;value:string;note:string}>;columns:string[];rows:string[][];statusIndex?:number;filters:string[]}
const metric=(a:string,b:string,c:string):Array<{label:string;value:string;note:string}>=>[{label:a,value:"—",note:"محدّث تلقائيًا"},{label:b,value:"—",note:"في الفرع الحالي"},{label:c,value:"—",note:"آخر تحديث الآن"}]
const common={statusIndex:5,filters:["كل الحالات","الفرع","الفترة"]}
export const sections:Record<string,SectionConfig>={
members:{...common,statusIndex:6,title:"دليل الأعضاء",eyebrow:"إدارة الأعضاء",description:"البحث في ملفات الأعضاء ومتابعة الرقم الجديد ورقم النظام القديم والحالة والفرع.",action:"تسجيل عضو جديد",search:"ابحث بالاسم أو رقم العضوية الجديد أو القديم...",listOperationId:"listMembers",createOperationId:"registerMember",fields:["name","memberNumber","legacyMemberNumber","phoneE164","branchName","registeredOn","status"],metrics:metric("إجمالي الأعضاء","أعضاء نشطون","غير نشطين"),columns:["العضو","رقم العضوية الجديد","رقم النظام القديم","الجوال","الفرع","تاريخ التسجيل","الحالة"],rows:[]},
 subscriptions:{...common,title:"الاشتراكات",eyebrow:"المبيعات والعضويات",description:"إدارة دورة حياة الاشتراك والتفعيل والتجميد والتجديد.",action:"اشتراك جديد",search:"ابحث برقم الاشتراك أو العضو...",listOperationId:"listSubscriptions",createOperationId:"createSubscription",fields:["subscriptionNumber","memberName","packageName","startsOn","endsOn","status"],metrics:metric("اشتراكات نشطة","مجمّدة","تنتهي قريبًا"),columns:["الاشتراك","العضو","الباقة","البداية","النهاية","الحالة"],rows:[]},
 attendance:{...common,title:"الحضور والدخول",eyebrow:"بوابة النادي",description:"تسجيل الزيارات ومراجعة حالات السماح بالدخول لحظة بلحظة.",action:"تسجيل دخول",search:"امسح البطاقة أو ابحث عن عضو...",listOperationId:"listAttendanceAttempts",createOperationId:"recordManualAttendance",fields:["memberName","memberNumber","occurredAt","method","branchName","decision"],metrics:metric("دخول اليوم","داخل النادي","محاولات مرفوضة"),columns:["العضو","رقم العضوية","الوقت","الطريقة","الفرع","القرار"],rows:[]},
 bookings:{...common,title:"الحجوزات والموارد",eyebrow:"المرافق والجدولة",description:"إدارة الحصص والملاعب ومواعيد التدريب والسعة المتاحة.",action:"حجز جديد",search:"ابحث عن حجز أو مورد...",listOperationId:"listReservations",createOperationId:"createManualReservation",fields:["reservationNumber","memberName","resourceName","startsAt","seats","status"],metrics:metric("حجوزات اليوم","نسبة الإشغال","مقاعد متاحة"),columns:["الحجز","العضو","المورد","الموعد","السعة","الحالة"],rows:[]},
 finance:{...common,title:"المبيعات والمالية",eyebrow:"المالية والنقدية",description:"الفواتير والمدفوعات والمصروفات والورديات النقدية.",action:"تسجيل دفعة",search:"ابحث برقم الفاتورة أو العميل...",listOperationId:"listInvoices",createOperationId:"recordPayment",fields:["invoiceNumber","buyerName","grossMinor","paidMinor","outstandingMinor","status"],metrics:metric("إيرادات اليوم","الرصيد المستحق","صافي النقدية"),columns:["الفاتورة","العميل","الإجمالي","المدفوع","المتبقي","الحالة"],rows:[]},
 crm:{...common,title:"العملاء المحتملون",eyebrow:"المبيعات والمتابعات",description:"متابعة الراغبين في الانضمام وتحويل الاهتمام إلى عضوية.",action:"إضافة عميل محتمل",search:"ابحث بالاسم أو وسيلة التواصل...",listOperationId:"listCrmLeads",createOperationId:"createCrmLead",fields:["fullName","sourceName","interest","assigneeName","nextFollowUpAt","status"],metrics:metric("فرص نشطة","متابعات اليوم","معدل التحويل"),columns:["الاسم","المصدر","الاهتمام","المسؤول","المتابعة","الحالة"],rows:[]},
 restaurant:{...common,title:"المطعم والمطبخ",eyebrow:"الطلبات وقائمة اليوم",description:"إدارة طابور المطبخ والوجبات واسترداد خطط الطعام.",action:"طلب جديد",search:"ابحث برقم الطلب أو العضو...",listOperationId:"listRestaurantOrders",createOperationId:"checkoutOrder",fields:["orderNumber","memberName","itemSummary","createdAt","grossMinor","status"],metrics:metric("طلبات اليوم","قيد التحضير","مبيعات المطعم"),columns:["الطلب","العضو","العناصر","الوقت","القيمة","الحالة"],rows:[]},
 staff:{...common,title:"الموظفون والمدربون",eyebrow:"القوى العاملة والتدريب",description:"الموظفون والمناوبات والحضور وتعيينات المدربين.",action:"إضافة موظف",search:"ابحث باسم الموظف أو المسمى...",listOperationId:"listEmployees",createOperationId:"createEmployee",fields:["fullNameAr","positionName","branchName","shiftSummary","attendanceAt","status"],metrics:metric("إجمالي الفريق","في المناوبة","جلسات اليوم"),columns:["الموظف","المسمى","الفرع","المناوبة","الحضور","الحالة"],rows:[]},
 reports:{...common,statusIndex:undefined,title:"التقارير والتحليلات",eyebrow:"مؤشرات الأداء",description:"النتائج اليومية الفعلية للفرع خلال آخر 30 يومًا، جاهزة للعرض والتصدير.",action:"إعادة بناء التقارير",search:"ابحث بالتاريخ أو القيمة...",listOperationId:"getBranchDailyReport",createOperationId:"requestReportingRebuild",fields:["businessDate","invoicedGrossMinor","collectedMinor","attendanceAccepted","newSubscriptions","asOf"],metrics:metric("أيام بها حركة","إجمالي الفواتير","إجمالي التحصيل"),columns:["يوم العمل","الفواتير","التحصيل","زيارات مقبولة","اشتراكات جديدة","آخر تحديث"],rows:[]},
settings:{...common,statusIndex:5,title:"حسابات النظام",eyebrow:"إدارة النظام",description:"الحسابات الداخلية المرتبطة بالنادي وحالتها الفعلية في قاعدة البيانات.",action:"إضافة حساب",search:"ابحث باسم الموظف أو البريد أو رقم الجوال...",listOperationId:"listUserAccounts",createOperationId:"provisionUserAccount",fields:["displayName","email","phoneE164","createdAt","updatedAt","status"],metrics:metric("حسابات الصفحة","حسابات نشطة","حسابات موقوفة"),columns:["اسم الموظف / الحساب","البريد الإلكتروني","الجوال","تاريخ الإنشاء","آخر تحديث","الحالة"],rows:[]},
}

