"use client"
import { useEffect, useState } from "react"
import { KeyRound, Loader2, QrCode, ShieldCheck } from "lucide-react"
import { apiRequest, hasRuntimeApi, setSession } from "@/lib/api-client"
import { humanError } from "@/lib/human-errors"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
type Factor={id:string;friendlyName?:string;status?:string}
export default function MfaPage(){const [factors,setFactors]=useState<Factor[]>([]);const [factorId,setFactorId]=useState("");const [challengeId,setChallengeId]=useState("");const [code,setCode]=useState("");const [enrollment,setEnrollment]=useState<{id?:string;qrCode?:string;secret?:string}>();const [loading,setLoading]=useState(false);const [message,setMessage]=useState("")
 useEffect(()=>{if(!hasRuntimeApi())return;const frame=requestAnimationFrame(()=>apiRequest<Factor[]>("/auth/mfa/factors").then(r=>setFactors(Array.isArray(r.data)?r.data:[])));return()=>cancelAnimationFrame(frame)},[])
 async function enroll(){setLoading(true);setMessage("");try{const r=await apiRequest<typeof enrollment>("/auth/mfa/enrollments",{method:"POST",body:"{}"});setEnrollment(r.data);if(r.data?.id)setFactorId(r.data.id)}catch(error){setMessage(humanError(error,"تعذر بدء الإعداد. حاول مرة أخرى."))}finally{setLoading(false)}}
 async function challenge(){setLoading(true);setMessage("");try{const r=await apiRequest<{challengeId:string}>("/auth/mfa/challenges",{method:"POST",body:JSON.stringify({factorId})});setChallengeId(r.data.challengeId);setMessage("أدخل الرمز الظاهر في تطبيق المصادقة") }catch(error){setMessage(humanError(error,"تعذر إرسال طلب التحقق. حاول مرة أخرى."))}finally{setLoading(false)}}
 async function verify(){setLoading(true);try{const r=await apiRequest<{accessToken:string;refreshToken:string}>("/auth/mfa/verifications",{method:"POST",body:JSON.stringify({factorId,challengeId,code})});await setSession(r.data);setMessage("تم تفعيل الحماية الإضافية لهذه الجلسة بنجاح.") }catch(error){setMessage(humanError(error,"الرمز غير صحيح أو انتهت صلاحيته. حاول مرة أخرى."))}finally{setLoading(false)}}
 return <div className="mx-auto max-w-3xl fade-up"><Badge variant="outline"><ShieldCheck/>أمان الحساب</Badge><h1 className="mt-4 text-3xl font-black">الحماية بخطوتين</h1><p className="mt-2 text-sm leading-7 text-muted-foreground">اربط تطبيق المصادقة لحماية الإجراءات المهمة برمز إضافي من 6 أرقام.</p><Card className="mt-7"><CardHeader><CardTitle>تطبيقات المصادقة</CardTitle><Badge variant={factors.length?"success":"warning"}>{factors.length?`${factors.length} تطبيق مرتبط`:"لم يتم الربط بعد"}</Badge></CardHeader><CardContent className="space-y-4">{factors.map(f=><button key={f.id} onClick={()=>setFactorId(f.id)} className={`flex w-full items-center rounded-xl border p-4 text-right ${factorId===f.id?"border-primary":""}`}><KeyRound className="text-amber-600"/><span className="mr-3 text-xs font-bold">{f.friendlyName??"تطبيق المصادقة"}</span><Badge variant="success" className="mr-auto">مفعّل</Badge></button>)}{enrollment&&<div className="rounded-xl bg-secondary p-4"><QrCode className="text-amber-600"/><p className="mt-3 text-xs font-bold">امسح الرمز المربع داخل تطبيق المصادقة</p>{enrollment.qrCode&&<div className="mt-3 overflow-auto rounded-lg bg-white p-3" dangerouslySetInnerHTML={{__html:enrollment.qrCode}}/>}<p className="mt-3 text-[10px] leading-5 text-muted-foreground">إذا تعذر المسح، أدخل المفتاح التالي يدويًا واحتفظ به في مكان آمن.</p><p dir="ltr" className="mt-2 rounded-lg bg-black p-3 text-center font-mono text-xs text-primary">{enrollment.secret}</p></div>}<div className="flex flex-wrap gap-2"><Button onClick={enroll} disabled={loading} variant="outline">ربط تطبيق جديد</Button><Button onClick={challenge} disabled={!factorId||loading}>استخدام رمز التحقق</Button></div>{challengeId&&<div className="flex gap-2"><Input dir="ltr" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} className="h-12 text-center text-xl tracking-[.4em]" placeholder="000000"/><Button size="lg" onClick={verify} disabled={code.length!==6||loading}>{loading?<Loader2 className="animate-spin"/>:"تأكيد"}</Button></div>}{message&&<p className="rounded-xl bg-secondary p-3 text-xs">{message}</p>}</CardContent></Card></div>}
